"""added authenticated at field

Revision ID: 4bb95c8aaab4
Revises: de8ff82b2dfc
Create Date: 2025-10-26 11:40:13.557744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb95c8aaab4'
down_revision: Union[str, Sequence[str], None] = 'de8ff82b2dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'pricing_tier',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pricing_tier',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('users', 'authenticated_at')
    # ### end Alembic commands ###
