"""Added conf field to moderator_deployments

Revision ID: 7fc4741da732
Revises: 8fe46c47c445
Create Date: 2025-10-16 10:58:04.037105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fc4741da732'
down_revision: Union[str, Sequence[str], None] = '8fe46c47c445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_deployments', sa.Column('conf', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_deployments', 'conf')
    # ### end Alembic commands ###
