"""added deployment_id field to moderator_logs

Revision ID: 88a07775aca2
Revises: 78297bb4fe49
Create Date: 2025-10-20 00:21:39.150333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a07775aca2'
down_revision: Union[str, Sequence[str], None] = '78297bb4fe49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_logs', sa.Column('deployment_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'moderator_logs', 'moderator_deployments', ['deployment_id'], ['deployment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moderator_logs', type_='foreignkey')
    op.drop_column('moderator_logs', 'deployment_id')
    # ### end Alembic commands ###
