"""added deployment_id field to message evaluations

Revision ID: aa2c69d52734
Revises: 88a07775aca2
Create Date: 2025-10-20 09:15:18.898735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2c69d52734'
down_revision: Union[str, Sequence[str], None] = '88a07775aca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('deployment_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deployment_id')
    # ### end Alembic commands ###
