"""created separate messages and message_evaluations tables

Revision ID: ee70ed94a2a1
Revises: aa2c69d52734
Create Date: 2025-10-20 09:33:52.131414

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee70ed94a2a1'
down_revision: Union[str, Sequence[str], None] = 'aa2c69d52734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_evaluations',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('topic_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.drop_column('messages', 'topic_score')
    op.drop_column('messages', 'topic')
    op.drop_column('messages', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('topic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('message_evaluations')
    # ### end Alembic commands ###
