"""Added name field to moderator_deployments

Revision ID: f9edc44f4894
Revises: 7fc4741da732
Create Date: 2025-10-16 11:00:33.030718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9edc44f4894'
down_revision: Union[str, Sequence[str], None] = '7fc4741da732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_deployments', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_deployments', 'name')
    # ### end Alembic commands ###
