/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Action Definitions API
 * Automatically generated from Pydantic models for action definitions.
 * OpenAPI spec version: 0.0.0
 */
/**
 * The client facing model(s) which allow prefilling
parameters. Used in the platforms config for defining
the allowed actions.
 */
export interface BaseActionDefinition {
  type: unknown;
  requires_approval: boolean;
}

export interface BanActionDefinition {
  type?: unknown;
  requires_approval: boolean;
}

/**
 * Duration in milliseconds to mute the user.
 */
export type MuteActionDefinitionDuration = number | null;

export interface MuteActionDefinition {
  type?: unknown;
  requires_approval: boolean;
  /** Duration in milliseconds to mute the user. */
  duration?: MuteActionDefinitionDuration;
}
