/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from "./lib/custom-fetch";
export interface DeploymentResponse {
  deployment_id: string;
  moderator_id: string;
  platform: MessagePlatformType;
  name: string;
  conf: DiscordConfigOutput;
  state: ModeratorDeploymentState;
  created_at: string;
}

export type DeploymentUpdateName = string | null;

export type DeploymentUpdateConfAnyOf = { [key: string]: unknown };

export type DeploymentUpdateConf = DeploymentUpdateConfAnyOf | null;

export interface DeploymentUpdate {
  name?: DeploymentUpdateName;
  conf?: DeploymentUpdateConf;
}

export interface DiscordAction {
  type: DiscordActionType;
  reason: string;
}

export type DiscordActionType =
  (typeof DiscordActionType)[keyof typeof DiscordActionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscordActionType = {
  ban: "ban",
  mute: "mute",
} as const;

export interface DiscordConfigInput {
  guild_id: number;
  allowed_channels: number[];
  allowed_actions: DiscordAction[];
}

export interface DiscordConfigOutput {
  guild_id: number;
  allowed_channels: number[];
  allowed_actions: DiscordAction[];
}

export interface GuidelineCreate {
  name: string;
  text: string;
}

export interface GuidelineResponse {
  name: string;
  text: string;
  guideline_id: string;
  created_at: string;
  topics: string[];
}

export type GuidelineUpdateName = string | null;

export type GuidelineUpdateText = string | null;

export interface GuidelineUpdate {
  name?: GuidelineUpdateName;
  text?: GuidelineUpdateText;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type MessagePlatformType =
  (typeof MessagePlatformType)[keyof typeof MessagePlatformType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessagePlatformType = {
  discord: "discord",
} as const;

export interface ModeratorCreate {
  name: string;
  guideline_id: string;
}

export type ModeratorDeploymentCreateName = string | null;

export type ModeratorDeploymentCreateConf = { [key: string]: unknown };

export interface ModeratorDeploymentCreate {
  platform: MessagePlatformType;
  name: ModeratorDeploymentCreateName;
  conf: ModeratorDeploymentCreateConf;
}

export interface ModeratorDeploymentResponse {
  deployment_id: string;
  moderator_id: string;
  platform: MessagePlatformType;
  conf: DiscordConfigOutput;
  state: ModeratorDeploymentState;
  created_at: string;
}

export type ModeratorDeploymentState =
  (typeof ModeratorDeploymentState)[keyof typeof ModeratorDeploymentState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModeratorDeploymentState = {
  offline: "offline",
  pending: "pending",
  online: "online",
} as const;

export interface ModeratorResponse {
  name: string;
  guideline_id: string;
  moderator_id: string;
  created_at: string;
}

export type ModeratorUpdateName = string | null;

export type ModeratorUpdateGuidelineId = string | null;

export interface ModeratorUpdate {
  name?: ModeratorUpdateName;
  guideline_id?: ModeratorUpdateGuidelineId;
}

export interface PaginatedResponseDeploymentResponse {
  page: number;
  size: number;
  has_next: boolean;
  data: DeploymentResponse[];
}

export interface PaginatedResponseGuidelineResponse {
  page: number;
  size: number;
  has_next: boolean;
  data: GuidelineResponse[];
}

export interface UserCreate {
  username: string;
  password: string;
}

export interface UserLogin {
  username: string;
  password: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type DiscordCallbackAuthDiscordOauthGetParams = {
  code: string;
};

export type ListDeploymentsDeploymentsGetParams = {
  /**
   * @minimum 1
   */
  page: number;
};

export type ListGuidelinesGuidelinesGetParams = {
  /**
   * @minimum 1
   */
  page: number;
};

export type ListModeratorsModeratorsGetParams = {
  /**
   * @minimum 1
   */
  page: number;
};

/**
 * @summary Register
 */
export type registerAuthRegisterPostResponse200 = {
  data: unknown;
  status: 200;
};

export type registerAuthRegisterPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type registerAuthRegisterPostResponseSuccess =
  registerAuthRegisterPostResponse200 & {
    headers: Headers;
  };
export type registerAuthRegisterPostResponseError =
  registerAuthRegisterPostResponse422 & {
    headers: Headers;
  };

export type registerAuthRegisterPostResponse =
  | registerAuthRegisterPostResponseSuccess
  | registerAuthRegisterPostResponseError;

export const getRegisterAuthRegisterPostUrl = () => {
  return `/auth/register`;
};

export const registerAuthRegisterPost = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<registerAuthRegisterPostResponse> => {
  return customFetch<registerAuthRegisterPostResponse>(
    getRegisterAuthRegisterPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userCreate),
    },
  );
};

/**
 * @summary Login
 */
export type loginAuthLoginPostResponse200 = {
  data: unknown;
  status: 200;
};

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginAuthLoginPostResponseSuccess =
  loginAuthLoginPostResponse200 & {
    headers: Headers;
  };
export type loginAuthLoginPostResponseError = loginAuthLoginPostResponse422 & {
  headers: Headers;
};

export type loginAuthLoginPostResponse =
  | loginAuthLoginPostResponseSuccess
  | loginAuthLoginPostResponseError;

export const getLoginAuthLoginPostUrl = () => {
  return `/auth/login`;
};

export const loginAuthLoginPost = async (
  userLogin: UserLogin,
  options?: RequestInit,
): Promise<loginAuthLoginPostResponse> => {
  return customFetch<loginAuthLoginPostResponse>(getLoginAuthLoginPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userLogin),
  });
};

/**
 * @summary Discord Callback
 */
export type discordCallbackAuthDiscordOauthGetResponse200 = {
  data: unknown;
  status: 200;
};

export type discordCallbackAuthDiscordOauthGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type discordCallbackAuthDiscordOauthGetResponseSuccess =
  discordCallbackAuthDiscordOauthGetResponse200 & {
    headers: Headers;
  };
export type discordCallbackAuthDiscordOauthGetResponseError =
  discordCallbackAuthDiscordOauthGetResponse422 & {
    headers: Headers;
  };

export type discordCallbackAuthDiscordOauthGetResponse =
  | discordCallbackAuthDiscordOauthGetResponseSuccess
  | discordCallbackAuthDiscordOauthGetResponseError;

export const getDiscordCallbackAuthDiscordOauthGetUrl = (
  params: DiscordCallbackAuthDiscordOauthGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/discord/oauth?${stringifiedParams}`
    : `/auth/discord/oauth`;
};

export const discordCallbackAuthDiscordOauthGet = async (
  params: DiscordCallbackAuthDiscordOauthGetParams,
  options?: RequestInit,
): Promise<discordCallbackAuthDiscordOauthGetResponse> => {
  return customFetch<discordCallbackAuthDiscordOauthGetResponse>(
    getDiscordCallbackAuthDiscordOauthGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List Deployments
 */
export type listDeploymentsDeploymentsGetResponse200 = {
  data: PaginatedResponseDeploymentResponse;
  status: 200;
};

export type listDeploymentsDeploymentsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listDeploymentsDeploymentsGetResponseSuccess =
  listDeploymentsDeploymentsGetResponse200 & {
    headers: Headers;
  };
export type listDeploymentsDeploymentsGetResponseError =
  listDeploymentsDeploymentsGetResponse422 & {
    headers: Headers;
  };

export type listDeploymentsDeploymentsGetResponse =
  | listDeploymentsDeploymentsGetResponseSuccess
  | listDeploymentsDeploymentsGetResponseError;

export const getListDeploymentsDeploymentsGetUrl = (
  params: ListDeploymentsDeploymentsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/deployments/?${stringifiedParams}`
    : `/deployments/`;
};

export const listDeploymentsDeploymentsGet = async (
  params: ListDeploymentsDeploymentsGetParams,
  options?: RequestInit,
): Promise<listDeploymentsDeploymentsGetResponse> => {
  return customFetch<listDeploymentsDeploymentsGetResponse>(
    getListDeploymentsDeploymentsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Deployment
 */
export type getDeploymentDeploymentsDeploymentIdGetResponse200 = {
  data: DeploymentResponse;
  status: 200;
};

export type getDeploymentDeploymentsDeploymentIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getDeploymentDeploymentsDeploymentIdGetResponseSuccess =
  getDeploymentDeploymentsDeploymentIdGetResponse200 & {
    headers: Headers;
  };
export type getDeploymentDeploymentsDeploymentIdGetResponseError =
  getDeploymentDeploymentsDeploymentIdGetResponse422 & {
    headers: Headers;
  };

export type getDeploymentDeploymentsDeploymentIdGetResponse =
  | getDeploymentDeploymentsDeploymentIdGetResponseSuccess
  | getDeploymentDeploymentsDeploymentIdGetResponseError;

export const getGetDeploymentDeploymentsDeploymentIdGetUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}`;
};

export const getDeploymentDeploymentsDeploymentIdGet = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<getDeploymentDeploymentsDeploymentIdGetResponse> => {
  return customFetch<getDeploymentDeploymentsDeploymentIdGetResponse>(
    getGetDeploymentDeploymentsDeploymentIdGetUrl(deploymentId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update Deployment
 */
export type updateDeploymentDeploymentsDeploymentIdPutResponse200 = {
  data: DeploymentResponse;
  status: 200;
};

export type updateDeploymentDeploymentsDeploymentIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateDeploymentDeploymentsDeploymentIdPutResponseSuccess =
  updateDeploymentDeploymentsDeploymentIdPutResponse200 & {
    headers: Headers;
  };
export type updateDeploymentDeploymentsDeploymentIdPutResponseError =
  updateDeploymentDeploymentsDeploymentIdPutResponse422 & {
    headers: Headers;
  };

export type updateDeploymentDeploymentsDeploymentIdPutResponse =
  | updateDeploymentDeploymentsDeploymentIdPutResponseSuccess
  | updateDeploymentDeploymentsDeploymentIdPutResponseError;

export const getUpdateDeploymentDeploymentsDeploymentIdPutUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}`;
};

export const updateDeploymentDeploymentsDeploymentIdPut = async (
  deploymentId: string,
  deploymentUpdate: DeploymentUpdate,
  options?: RequestInit,
): Promise<updateDeploymentDeploymentsDeploymentIdPutResponse> => {
  return customFetch<updateDeploymentDeploymentsDeploymentIdPutResponse>(
    getUpdateDeploymentDeploymentsDeploymentIdPutUrl(deploymentId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(deploymentUpdate),
    },
  );
};

/**
 * @summary Delete Deployment
 */
export type deleteDeploymentDeploymentsDeploymentIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteDeploymentDeploymentsDeploymentIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteDeploymentDeploymentsDeploymentIdDeleteResponseSuccess =
  deleteDeploymentDeploymentsDeploymentIdDeleteResponse200 & {
    headers: Headers;
  };
export type deleteDeploymentDeploymentsDeploymentIdDeleteResponseError =
  deleteDeploymentDeploymentsDeploymentIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteDeploymentDeploymentsDeploymentIdDeleteResponse =
  | deleteDeploymentDeploymentsDeploymentIdDeleteResponseSuccess
  | deleteDeploymentDeploymentsDeploymentIdDeleteResponseError;

export const getDeleteDeploymentDeploymentsDeploymentIdDeleteUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}`;
};

export const deleteDeploymentDeploymentsDeploymentIdDelete = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<deleteDeploymentDeploymentsDeploymentIdDeleteResponse> => {
  return customFetch<deleteDeploymentDeploymentsDeploymentIdDeleteResponse>(
    getDeleteDeploymentDeploymentsDeploymentIdDeleteUrl(deploymentId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Create Guideline
 */
export type createGuidelineGuidelinesPostResponse200 = {
  data: GuidelineResponse;
  status: 200;
};

export type createGuidelineGuidelinesPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createGuidelineGuidelinesPostResponseSuccess =
  createGuidelineGuidelinesPostResponse200 & {
    headers: Headers;
  };
export type createGuidelineGuidelinesPostResponseError =
  createGuidelineGuidelinesPostResponse422 & {
    headers: Headers;
  };

export type createGuidelineGuidelinesPostResponse =
  | createGuidelineGuidelinesPostResponseSuccess
  | createGuidelineGuidelinesPostResponseError;

export const getCreateGuidelineGuidelinesPostUrl = () => {
  return `/guidelines/`;
};

export const createGuidelineGuidelinesPost = async (
  guidelineCreate: GuidelineCreate,
  options?: RequestInit,
): Promise<createGuidelineGuidelinesPostResponse> => {
  return customFetch<createGuidelineGuidelinesPostResponse>(
    getCreateGuidelineGuidelinesPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(guidelineCreate),
    },
  );
};

/**
 * @summary List Guidelines
 */
export type listGuidelinesGuidelinesGetResponse200 = {
  data: PaginatedResponseGuidelineResponse;
  status: 200;
};

export type listGuidelinesGuidelinesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listGuidelinesGuidelinesGetResponseSuccess =
  listGuidelinesGuidelinesGetResponse200 & {
    headers: Headers;
  };
export type listGuidelinesGuidelinesGetResponseError =
  listGuidelinesGuidelinesGetResponse422 & {
    headers: Headers;
  };

export type listGuidelinesGuidelinesGetResponse =
  | listGuidelinesGuidelinesGetResponseSuccess
  | listGuidelinesGuidelinesGetResponseError;

export const getListGuidelinesGuidelinesGetUrl = (
  params: ListGuidelinesGuidelinesGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/guidelines/?${stringifiedParams}`
    : `/guidelines/`;
};

export const listGuidelinesGuidelinesGet = async (
  params: ListGuidelinesGuidelinesGetParams,
  options?: RequestInit,
): Promise<listGuidelinesGuidelinesGetResponse> => {
  return customFetch<listGuidelinesGuidelinesGetResponse>(
    getListGuidelinesGuidelinesGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Guideline
 */
export type getGuidelineGuidelinesGuidelineIdGetResponse200 = {
  data: GuidelineResponse;
  status: 200;
};

export type getGuidelineGuidelinesGuidelineIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getGuidelineGuidelinesGuidelineIdGetResponseSuccess =
  getGuidelineGuidelinesGuidelineIdGetResponse200 & {
    headers: Headers;
  };
export type getGuidelineGuidelinesGuidelineIdGetResponseError =
  getGuidelineGuidelinesGuidelineIdGetResponse422 & {
    headers: Headers;
  };

export type getGuidelineGuidelinesGuidelineIdGetResponse =
  | getGuidelineGuidelinesGuidelineIdGetResponseSuccess
  | getGuidelineGuidelinesGuidelineIdGetResponseError;

export const getGetGuidelineGuidelinesGuidelineIdGetUrl = (
  guidelineId: string,
) => {
  return `/guidelines/${guidelineId}`;
};

export const getGuidelineGuidelinesGuidelineIdGet = async (
  guidelineId: string,
  options?: RequestInit,
): Promise<getGuidelineGuidelinesGuidelineIdGetResponse> => {
  return customFetch<getGuidelineGuidelinesGuidelineIdGetResponse>(
    getGetGuidelineGuidelinesGuidelineIdGetUrl(guidelineId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update Guideline
 */
export type updateGuidelineGuidelinesGuidelineIdPutResponse200 = {
  data: GuidelineResponse;
  status: 200;
};

export type updateGuidelineGuidelinesGuidelineIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateGuidelineGuidelinesGuidelineIdPutResponseSuccess =
  updateGuidelineGuidelinesGuidelineIdPutResponse200 & {
    headers: Headers;
  };
export type updateGuidelineGuidelinesGuidelineIdPutResponseError =
  updateGuidelineGuidelinesGuidelineIdPutResponse422 & {
    headers: Headers;
  };

export type updateGuidelineGuidelinesGuidelineIdPutResponse =
  | updateGuidelineGuidelinesGuidelineIdPutResponseSuccess
  | updateGuidelineGuidelinesGuidelineIdPutResponseError;

export const getUpdateGuidelineGuidelinesGuidelineIdPutUrl = (
  guidelineId: string,
) => {
  return `/guidelines/${guidelineId}`;
};

export const updateGuidelineGuidelinesGuidelineIdPut = async (
  guidelineId: string,
  guidelineUpdate: GuidelineUpdate,
  options?: RequestInit,
): Promise<updateGuidelineGuidelinesGuidelineIdPutResponse> => {
  return customFetch<updateGuidelineGuidelinesGuidelineIdPutResponse>(
    getUpdateGuidelineGuidelinesGuidelineIdPutUrl(guidelineId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(guidelineUpdate),
    },
  );
};

/**
 * @summary Delete Guideline
 */
export type deleteGuidelineGuidelinesGuidelineIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteGuidelineGuidelinesGuidelineIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteGuidelineGuidelinesGuidelineIdDeleteResponseSuccess =
  deleteGuidelineGuidelinesGuidelineIdDeleteResponse200 & {
    headers: Headers;
  };
export type deleteGuidelineGuidelinesGuidelineIdDeleteResponseError =
  deleteGuidelineGuidelinesGuidelineIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteGuidelineGuidelinesGuidelineIdDeleteResponse =
  | deleteGuidelineGuidelinesGuidelineIdDeleteResponseSuccess
  | deleteGuidelineGuidelinesGuidelineIdDeleteResponseError;

export const getDeleteGuidelineGuidelinesGuidelineIdDeleteUrl = (
  guidelineId: string,
) => {
  return `/guidelines/${guidelineId}`;
};

export const deleteGuidelineGuidelinesGuidelineIdDelete = async (
  guidelineId: string,
  options?: RequestInit,
): Promise<deleteGuidelineGuidelinesGuidelineIdDeleteResponse> => {
  return customFetch<deleteGuidelineGuidelinesGuidelineIdDeleteResponse>(
    getDeleteGuidelineGuidelinesGuidelineIdDeleteUrl(guidelineId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Create Moderator
 */
export type createModeratorModeratorsPostResponse200 = {
  data: ModeratorResponse;
  status: 200;
};

export type createModeratorModeratorsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createModeratorModeratorsPostResponseSuccess =
  createModeratorModeratorsPostResponse200 & {
    headers: Headers;
  };
export type createModeratorModeratorsPostResponseError =
  createModeratorModeratorsPostResponse422 & {
    headers: Headers;
  };

export type createModeratorModeratorsPostResponse =
  | createModeratorModeratorsPostResponseSuccess
  | createModeratorModeratorsPostResponseError;

export const getCreateModeratorModeratorsPostUrl = () => {
  return `/moderators/`;
};

export const createModeratorModeratorsPost = async (
  moderatorCreate: ModeratorCreate,
  options?: RequestInit,
): Promise<createModeratorModeratorsPostResponse> => {
  return customFetch<createModeratorModeratorsPostResponse>(
    getCreateModeratorModeratorsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(moderatorCreate),
    },
  );
};

/**
 * @summary List Moderators
 */
export type listModeratorsModeratorsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type listModeratorsModeratorsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listModeratorsModeratorsGetResponseSuccess =
  listModeratorsModeratorsGetResponse200 & {
    headers: Headers;
  };
export type listModeratorsModeratorsGetResponseError =
  listModeratorsModeratorsGetResponse422 & {
    headers: Headers;
  };

export type listModeratorsModeratorsGetResponse =
  | listModeratorsModeratorsGetResponseSuccess
  | listModeratorsModeratorsGetResponseError;

export const getListModeratorsModeratorsGetUrl = (
  params: ListModeratorsModeratorsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/moderators/?${stringifiedParams}`
    : `/moderators/`;
};

export const listModeratorsModeratorsGet = async (
  params: ListModeratorsModeratorsGetParams,
  options?: RequestInit,
): Promise<listModeratorsModeratorsGetResponse> => {
  return customFetch<listModeratorsModeratorsGetResponse>(
    getListModeratorsModeratorsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Deploy Moderator
 */
export type deployModeratorModeratorsDeployModeratorIdPostResponse200 = {
  data: ModeratorDeploymentResponse;
  status: 200;
};

export type deployModeratorModeratorsDeployModeratorIdPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deployModeratorModeratorsDeployModeratorIdPostResponseSuccess =
  deployModeratorModeratorsDeployModeratorIdPostResponse200 & {
    headers: Headers;
  };
export type deployModeratorModeratorsDeployModeratorIdPostResponseError =
  deployModeratorModeratorsDeployModeratorIdPostResponse422 & {
    headers: Headers;
  };

export type deployModeratorModeratorsDeployModeratorIdPostResponse =
  | deployModeratorModeratorsDeployModeratorIdPostResponseSuccess
  | deployModeratorModeratorsDeployModeratorIdPostResponseError;

export const getDeployModeratorModeratorsDeployModeratorIdPostUrl = (
  moderatorId: string,
) => {
  return `/moderators/deploy/${moderatorId}`;
};

export const deployModeratorModeratorsDeployModeratorIdPost = async (
  moderatorId: string,
  moderatorDeploymentCreate: ModeratorDeploymentCreate,
  options?: RequestInit,
): Promise<deployModeratorModeratorsDeployModeratorIdPostResponse> => {
  return customFetch<deployModeratorModeratorsDeployModeratorIdPostResponse>(
    getDeployModeratorModeratorsDeployModeratorIdPostUrl(moderatorId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(moderatorDeploymentCreate),
    },
  );
};

/**
 * @summary Get Moderator
 */
export type getModeratorModeratorsModeratorIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getModeratorModeratorsModeratorIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getModeratorModeratorsModeratorIdGetResponseSuccess =
  getModeratorModeratorsModeratorIdGetResponse200 & {
    headers: Headers;
  };
export type getModeratorModeratorsModeratorIdGetResponseError =
  getModeratorModeratorsModeratorIdGetResponse422 & {
    headers: Headers;
  };

export type getModeratorModeratorsModeratorIdGetResponse =
  | getModeratorModeratorsModeratorIdGetResponseSuccess
  | getModeratorModeratorsModeratorIdGetResponseError;

export const getGetModeratorModeratorsModeratorIdGetUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const getModeratorModeratorsModeratorIdGet = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<getModeratorModeratorsModeratorIdGetResponse> => {
  return customFetch<getModeratorModeratorsModeratorIdGetResponse>(
    getGetModeratorModeratorsModeratorIdGetUrl(moderatorId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update Moderator
 */
export type updateModeratorModeratorsModeratorIdPutResponse200 = {
  data: unknown;
  status: 200;
};

export type updateModeratorModeratorsModeratorIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateModeratorModeratorsModeratorIdPutResponseSuccess =
  updateModeratorModeratorsModeratorIdPutResponse200 & {
    headers: Headers;
  };
export type updateModeratorModeratorsModeratorIdPutResponseError =
  updateModeratorModeratorsModeratorIdPutResponse422 & {
    headers: Headers;
  };

export type updateModeratorModeratorsModeratorIdPutResponse =
  | updateModeratorModeratorsModeratorIdPutResponseSuccess
  | updateModeratorModeratorsModeratorIdPutResponseError;

export const getUpdateModeratorModeratorsModeratorIdPutUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const updateModeratorModeratorsModeratorIdPut = async (
  moderatorId: string,
  moderatorUpdate: ModeratorUpdate,
  options?: RequestInit,
): Promise<updateModeratorModeratorsModeratorIdPutResponse> => {
  return customFetch<updateModeratorModeratorsModeratorIdPutResponse>(
    getUpdateModeratorModeratorsModeratorIdPutUrl(moderatorId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(moderatorUpdate),
    },
  );
};

/**
 * @summary Delete Moderator
 */
export type deleteModeratorModeratorsModeratorIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteModeratorModeratorsModeratorIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteModeratorModeratorsModeratorIdDeleteResponseSuccess =
  deleteModeratorModeratorsModeratorIdDeleteResponse200 & {
    headers: Headers;
  };
export type deleteModeratorModeratorsModeratorIdDeleteResponseError =
  deleteModeratorModeratorsModeratorIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteModeratorModeratorsModeratorIdDeleteResponse =
  | deleteModeratorModeratorsModeratorIdDeleteResponseSuccess
  | deleteModeratorModeratorsModeratorIdDeleteResponseError;

export const getDeleteModeratorModeratorsModeratorIdDeleteUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const deleteModeratorModeratorsModeratorIdDelete = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<deleteModeratorModeratorsModeratorIdDeleteResponse> => {
  return customFetch<deleteModeratorModeratorsModeratorIdDeleteResponse>(
    getDeleteModeratorModeratorsModeratorIdDeleteUrl(moderatorId),
    {
      ...options,
      method: "DELETE",
    },
  );
};
