/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from "./lib/custom-fetch";
export type ActionStatus = (typeof ActionStatus)[keyof typeof ActionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionStatus = {
  failed: "failed",
  pending: "pending",
  success: "success",
  declined: "declined",
  awaiting_approval: "awaiting_approval",
  approved: "approved",
} as const;

export type ActionUpdateStatus =
  (typeof ActionUpdateStatus)[keyof typeof ActionUpdateStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionUpdateStatus = {
  approved: "approved",
  declined: "declined",
} as const;

export interface ActionUpdate {
  status: ActionUpdateStatus;
}

/**
 * The client facing model(s) which allow prefilling
parameters. Used in the platforms config for defining
the allowed actions.
 */
export interface BaseActionDefinition {
  type: unknown;
  requires_approval: boolean;
}

export type BodyListDeploymentsDeploymentsGetStatus =
  | ModeratorDeploymentStatus[]
  | null;

export type BodyListDeploymentsDeploymentsGetPlatform =
  | MessagePlatformType[]
  | null;

export interface BodyListDeploymentsDeploymentsGet {
  status?: BodyListDeploymentsDeploymentsGetStatus;
  platform?: BodyListDeploymentsDeploymentsGetPlatform;
}

export type ConnectionType =
  (typeof ConnectionType)[keyof typeof ConnectionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConnectionType = {
  discord: "discord",
} as const;

export interface ContactForm {
  name: string;
  email: string;
  message: string;
}

export type DeploymentActionActionParams = { [key: string]: unknown };

export interface DeploymentAction {
  log_id: string;
  deployment_id: string;
  action_type: string;
  action_params: DeploymentActionActionParams;
  status: ActionStatus;
  created_at: string;
}

export type DeploymentCreateName = string | null;

export type DeploymentCreateConf = { [key: string]: unknown };

export interface DeploymentCreate {
  platform: MessagePlatformType;
  name: DeploymentCreateName;
  conf: DeploymentCreateConf;
}

export interface DeploymentResponse {
  deployment_id: string;
  moderator_id: string;
  platform: MessagePlatformType;
  name: string;
  conf: DiscordConfigResponse;
  status: ModeratorDeploymentStatus;
  created_at: string;
}

export interface DeploymentStats {
  total_messages: number;
  total_actions: number;
  message_chart: MessageChartData[];
}

export type DeploymentUpdateName = string | null;

export type DeploymentUpdateConfAnyOf = { [key: string]: unknown };

export type DeploymentUpdateConf = DeploymentUpdateConfAnyOf | null;

export interface DeploymentUpdate {
  name?: DeploymentUpdateName;
  conf?: DeploymentUpdateConf;
}

export type DiscordConfigResponseAllowedChannels = ["*"] | number[];

export type DiscordConfigResponseAllowedActions =
  | ["*"]
  | BaseActionDefinition[];

export interface DiscordConfigResponse {
  guild_id: string;
  allowed_channels: DiscordConfigResponseAllowedChannels;
  allowed_actions: DiscordConfigResponseAllowedActions;
}

export interface GuidelineCreate {
  name: string;
  text: string;
}

export interface GuidelineResponse {
  name: string;
  text: string;
  guideline_id: string;
  created_at: string;
  topics: string[];
}

export type GuidelineUpdateName = string | null;

export type GuidelineUpdateText = string | null;

export interface GuidelineUpdate {
  name?: GuidelineUpdateName;
  text?: GuidelineUpdateText;
}

export type GuildIcon = string | null;

export interface Guild {
  id: string;
  name: string;
  icon: GuildIcon;
}

export interface GuildChannel {
  id: string;
  name: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type MessageChartDataCounts = { [key: string]: number };

export interface MessageChartData {
  date: string;
  counts: MessageChartDataCounts;
}

export type MessagePlatformType =
  (typeof MessagePlatformType)[keyof typeof MessagePlatformType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessagePlatformType = {
  discord: "discord",
} as const;

export interface ModeratorCreate {
  name: string;
  guideline_id: string;
}

export type ModeratorDeploymentStatus =
  (typeof ModeratorDeploymentStatus)[keyof typeof ModeratorDeploymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModeratorDeploymentStatus = {
  offline: "offline",
  pending: "pending",
  online: "online",
} as const;

export interface ModeratorResponse {
  name: string;
  guideline_id: string;
  moderator_id: string;
  created_at: string;
  deployment_platforms: MessagePlatformType[];
}

export interface ModeratorStats {
  total_messages: number;
  total_actions: number;
  message_chart: MessageChartData[];
}

export type ModeratorUpdateName = string | null;

export type ModeratorUpdateGuidelineId = string | null;

export interface ModeratorUpdate {
  name?: ModeratorUpdateName;
  guideline_id?: ModeratorUpdateGuidelineId;
}

export interface PaginatedResponseDeploymentAction {
  page: number;
  size: number;
  has_next: boolean;
  data: DeploymentAction[];
}

export interface PaginatedResponseDeploymentResponse {
  page: number;
  size: number;
  has_next: boolean;
  data: DeploymentResponse[];
}

export interface PaginatedResponseGuidelineResponse {
  page: number;
  size: number;
  has_next: boolean;
  data: GuidelineResponse[];
}

export interface PaginatedResponseModeratorResponse {
  page: number;
  size: number;
  has_next: boolean;
  data: ModeratorResponse[];
}

export interface PlatformConnection {
  username: string;
  avatar: string;
}

export type PricingTierType =
  (typeof PricingTierType)[keyof typeof PricingTierType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PricingTierType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface UpdatePassword {
  password: string;
}

export interface UpdateUsername {
  username: string;
}

export interface UserCreate {
  username: string;
  email: string;
  password: string;
}

export type UserLoginUsername = string | null;

export type UserLoginEmail = string | null;

export interface UserLogin {
  username?: UserLoginUsername;
  email?: UserLoginEmail;
  password: string;
}

export type UserMeConnectionsAnyOf = { [key: string]: PlatformConnection };

export type UserMeConnections = UserMeConnectionsAnyOf | null;

export interface UserMe {
  username: string;
  pricing_tier: PricingTierType;
  connections?: UserMeConnections;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type VerifyActionAction =
  (typeof VerifyActionAction)[keyof typeof VerifyActionAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyActionAction = {
  change_username: "change_username",
  change_password: "change_password",
} as const;

export interface VerifyAction {
  code: string;
  action: VerifyActionAction;
}

export interface VerifyCode {
  code: string;
}

export type DiscordCallbackAuthDiscordOauthGetParams = {
  code: string;
};

export type ListDeploymentsDeploymentsGetParams = {
  /**
   * @minimum 1
   */
  page: number;
  name?: string | null;
};

export type GetDeploymentActionsDeploymentsDeploymentIdActionsGetParams = {
  /**
   * @minimum 1
   */
  page?: number;
};

export type ListGuidelinesGuidelinesGetParams = {
  /**
   * @minimum 1
   */
  page: number;
  search?: string | null;
};

export type ListModeratorsModeratorsGetParams = {
  name?: string | null;
  /**
   * @minimum 1
   */
  page: number;
};

export type GetDeploymentsModeratorsModeratorIdDeploymentsGetParams = {
  /**
   * @minimum 1
   */
  page?: number;
};

/**
 * @summary Update Action Status
 */
export type updateActionStatusActionsLogIdPatchResponse200 = {
  data: unknown;
  status: 200;
};

export type updateActionStatusActionsLogIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateActionStatusActionsLogIdPatchResponseSuccess =
  updateActionStatusActionsLogIdPatchResponse200 & {
    headers: Headers;
  };
export type updateActionStatusActionsLogIdPatchResponseError =
  updateActionStatusActionsLogIdPatchResponse422 & {
    headers: Headers;
  };

export type updateActionStatusActionsLogIdPatchResponse =
  | updateActionStatusActionsLogIdPatchResponseSuccess
  | updateActionStatusActionsLogIdPatchResponseError;

export const getUpdateActionStatusActionsLogIdPatchUrl = (logId: string) => {
  return `/actions/${logId}`;
};

export const updateActionStatusActionsLogIdPatch = async (
  logId: string,
  actionUpdate: ActionUpdate,
  options?: RequestInit,
): Promise<updateActionStatusActionsLogIdPatchResponse> => {
  return customFetch<updateActionStatusActionsLogIdPatchResponse>(
    getUpdateActionStatusActionsLogIdPatchUrl(logId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(actionUpdate),
    },
  );
};

/**
 * @summary Register
 */
export type registerAuthRegisterPostResponse202 = {
  data: unknown;
  status: 202;
};

export type registerAuthRegisterPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type registerAuthRegisterPostResponseSuccess =
  registerAuthRegisterPostResponse202 & {
    headers: Headers;
  };
export type registerAuthRegisterPostResponseError =
  registerAuthRegisterPostResponse422 & {
    headers: Headers;
  };

export type registerAuthRegisterPostResponse =
  | registerAuthRegisterPostResponseSuccess
  | registerAuthRegisterPostResponseError;

export const getRegisterAuthRegisterPostUrl = () => {
  return `/auth/register`;
};

export const registerAuthRegisterPost = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<registerAuthRegisterPostResponse> => {
  return customFetch<registerAuthRegisterPostResponse>(
    getRegisterAuthRegisterPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userCreate),
    },
  );
};

/**
 * @summary Login
 */
export type loginAuthLoginPostResponse200 = {
  data: unknown;
  status: 200;
};

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginAuthLoginPostResponseSuccess =
  loginAuthLoginPostResponse200 & {
    headers: Headers;
  };
export type loginAuthLoginPostResponseError = loginAuthLoginPostResponse422 & {
  headers: Headers;
};

export type loginAuthLoginPostResponse =
  | loginAuthLoginPostResponseSuccess
  | loginAuthLoginPostResponseError;

export const getLoginAuthLoginPostUrl = () => {
  return `/auth/login`;
};

export const loginAuthLoginPost = async (
  userLogin: UserLogin,
  options?: RequestInit,
): Promise<loginAuthLoginPostResponse> => {
  return customFetch<loginAuthLoginPostResponse>(getLoginAuthLoginPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userLogin),
  });
};

/**
 * @summary Request Email Verification
 */
export type requestEmailVerificationAuthRequestEmailVerificationPostResponse200 =
  {
    data: unknown;
    status: 200;
  };

export type requestEmailVerificationAuthRequestEmailVerificationPostResponseSuccess =
  requestEmailVerificationAuthRequestEmailVerificationPostResponse200 & {
    headers: Headers;
  };
export type requestEmailVerificationAuthRequestEmailVerificationPostResponse =
  requestEmailVerificationAuthRequestEmailVerificationPostResponseSuccess;

export const getRequestEmailVerificationAuthRequestEmailVerificationPostUrl =
  () => {
    return `/auth/request-email-verification`;
  };

export const requestEmailVerificationAuthRequestEmailVerificationPost = async (
  options?: RequestInit,
): Promise<requestEmailVerificationAuthRequestEmailVerificationPostResponse> => {
  return customFetch<requestEmailVerificationAuthRequestEmailVerificationPostResponse>(
    getRequestEmailVerificationAuthRequestEmailVerificationPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Verify Email
 */
export type verifyEmailAuthVerifyEmailPostResponse200 = {
  data: unknown;
  status: 200;
};

export type verifyEmailAuthVerifyEmailPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type verifyEmailAuthVerifyEmailPostResponseSuccess =
  verifyEmailAuthVerifyEmailPostResponse200 & {
    headers: Headers;
  };
export type verifyEmailAuthVerifyEmailPostResponseError =
  verifyEmailAuthVerifyEmailPostResponse422 & {
    headers: Headers;
  };

export type verifyEmailAuthVerifyEmailPostResponse =
  | verifyEmailAuthVerifyEmailPostResponseSuccess
  | verifyEmailAuthVerifyEmailPostResponseError;

export const getVerifyEmailAuthVerifyEmailPostUrl = () => {
  return `/auth/verify-email`;
};

export const verifyEmailAuthVerifyEmailPost = async (
  verifyCode: VerifyCode,
  options?: RequestInit,
): Promise<verifyEmailAuthVerifyEmailPostResponse> => {
  return customFetch<verifyEmailAuthVerifyEmailPostResponse>(
    getVerifyEmailAuthVerifyEmailPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(verifyCode),
    },
  );
};

/**
 * @summary Logout
 */
export type logoutAuthLogoutPostResponse200 = {
  data: unknown;
  status: 200;
};

export type logoutAuthLogoutPostResponseSuccess =
  logoutAuthLogoutPostResponse200 & {
    headers: Headers;
  };
export type logoutAuthLogoutPostResponse = logoutAuthLogoutPostResponseSuccess;

export const getLogoutAuthLogoutPostUrl = () => {
  return `/auth/logout`;
};

export const logoutAuthLogoutPost = async (
  options?: RequestInit,
): Promise<logoutAuthLogoutPostResponse> => {
  return customFetch<logoutAuthLogoutPostResponse>(
    getLogoutAuthLogoutPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Get Me
 */
export type getMeAuthMeGetResponse200 = {
  data: UserMe;
  status: 200;
};

export type getMeAuthMeGetResponseSuccess = getMeAuthMeGetResponse200 & {
  headers: Headers;
};
export type getMeAuthMeGetResponse = getMeAuthMeGetResponseSuccess;

export const getGetMeAuthMeGetUrl = () => {
  return `/auth/me`;
};

export const getMeAuthMeGet = async (
  options?: RequestInit,
): Promise<getMeAuthMeGetResponse> => {
  return customFetch<getMeAuthMeGetResponse>(getGetMeAuthMeGetUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Discord Callback
 */
export type discordCallbackAuthDiscordOauthGetResponse200 = {
  data: unknown;
  status: 200;
};

export type discordCallbackAuthDiscordOauthGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type discordCallbackAuthDiscordOauthGetResponseSuccess =
  discordCallbackAuthDiscordOauthGetResponse200 & {
    headers: Headers;
  };
export type discordCallbackAuthDiscordOauthGetResponseError =
  discordCallbackAuthDiscordOauthGetResponse422 & {
    headers: Headers;
  };

export type discordCallbackAuthDiscordOauthGetResponse =
  | discordCallbackAuthDiscordOauthGetResponseSuccess
  | discordCallbackAuthDiscordOauthGetResponseError;

export const getDiscordCallbackAuthDiscordOauthGetUrl = (
  params: DiscordCallbackAuthDiscordOauthGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/discord/oauth?${stringifiedParams}`
    : `/auth/discord/oauth`;
};

export const discordCallbackAuthDiscordOauthGet = async (
  params: DiscordCallbackAuthDiscordOauthGetParams,
  options?: RequestInit,
): Promise<discordCallbackAuthDiscordOauthGetResponse> => {
  return customFetch<discordCallbackAuthDiscordOauthGetResponse>(
    getDiscordCallbackAuthDiscordOauthGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Change Username
 */
export type changeUsernameAuthChangeUsernamePostResponse202 = {
  data: unknown;
  status: 202;
};

export type changeUsernameAuthChangeUsernamePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type changeUsernameAuthChangeUsernamePostResponseSuccess =
  changeUsernameAuthChangeUsernamePostResponse202 & {
    headers: Headers;
  };
export type changeUsernameAuthChangeUsernamePostResponseError =
  changeUsernameAuthChangeUsernamePostResponse422 & {
    headers: Headers;
  };

export type changeUsernameAuthChangeUsernamePostResponse =
  | changeUsernameAuthChangeUsernamePostResponseSuccess
  | changeUsernameAuthChangeUsernamePostResponseError;

export const getChangeUsernameAuthChangeUsernamePostUrl = () => {
  return `/auth/change-username`;
};

export const changeUsernameAuthChangeUsernamePost = async (
  updateUsername: UpdateUsername,
  options?: RequestInit,
): Promise<changeUsernameAuthChangeUsernamePostResponse> => {
  return customFetch<changeUsernameAuthChangeUsernamePostResponse>(
    getChangeUsernameAuthChangeUsernamePostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateUsername),
    },
  );
};

/**
 * @summary Change Password
 */
export type changePasswordAuthChangePasswordPostResponse202 = {
  data: unknown;
  status: 202;
};

export type changePasswordAuthChangePasswordPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type changePasswordAuthChangePasswordPostResponseSuccess =
  changePasswordAuthChangePasswordPostResponse202 & {
    headers: Headers;
  };
export type changePasswordAuthChangePasswordPostResponseError =
  changePasswordAuthChangePasswordPostResponse422 & {
    headers: Headers;
  };

export type changePasswordAuthChangePasswordPostResponse =
  | changePasswordAuthChangePasswordPostResponseSuccess
  | changePasswordAuthChangePasswordPostResponseError;

export const getChangePasswordAuthChangePasswordPostUrl = () => {
  return `/auth/change-password`;
};

export const changePasswordAuthChangePasswordPost = async (
  updatePassword: UpdatePassword,
  options?: RequestInit,
): Promise<changePasswordAuthChangePasswordPostResponse> => {
  return customFetch<changePasswordAuthChangePasswordPostResponse>(
    getChangePasswordAuthChangePasswordPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updatePassword),
    },
  );
};

/**
 * @summary Verify Action
 */
export type verifyActionAuthVerifyActionPostResponse200 = {
  data: unknown;
  status: 200;
};

export type verifyActionAuthVerifyActionPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type verifyActionAuthVerifyActionPostResponseSuccess =
  verifyActionAuthVerifyActionPostResponse200 & {
    headers: Headers;
  };
export type verifyActionAuthVerifyActionPostResponseError =
  verifyActionAuthVerifyActionPostResponse422 & {
    headers: Headers;
  };

export type verifyActionAuthVerifyActionPostResponse =
  | verifyActionAuthVerifyActionPostResponseSuccess
  | verifyActionAuthVerifyActionPostResponseError;

export const getVerifyActionAuthVerifyActionPostUrl = () => {
  return `/auth/verify-action`;
};

export const verifyActionAuthVerifyActionPost = async (
  verifyAction: VerifyAction,
  options?: RequestInit,
): Promise<verifyActionAuthVerifyActionPostResponse> => {
  return customFetch<verifyActionAuthVerifyActionPostResponse>(
    getVerifyActionAuthVerifyActionPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(verifyAction),
    },
  );
};

/**
 * @summary Get Owned Discord Guilds
 */
export type getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse200 = {
  data: Guild[];
  status: 200;
};

export type getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponseSuccess =
  getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse200 & {
    headers: Headers;
  };
export type getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse =
  getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponseSuccess;

export const getGetOwnedDiscordGuildsConnectionsDiscordGuildsGetUrl = () => {
  return `/connections/discord/guilds`;
};

export const getOwnedDiscordGuildsConnectionsDiscordGuildsGet = async (
  options?: RequestInit,
): Promise<getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse> => {
  return customFetch<getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse>(
    getGetOwnedDiscordGuildsConnectionsDiscordGuildsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Discord Channels
 */
export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse200 =
  {
    data: GuildChannel[];
    status: 200;
  };

export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse422 =
  {
    data: HTTPValidationError;
    status: 422;
  };

export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponseSuccess =
  getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse200 & {
    headers: Headers;
  };
export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponseError =
  getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse422 & {
    headers: Headers;
  };

export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse =
  | getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponseSuccess
  | getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponseError;

export const getGetDiscordChannelsConnectionsDiscordGuildIdChannelsGetUrl = (
  guildId: string,
) => {
  return `/connections/discord/${guildId}/channels`;
};

export const getDiscordChannelsConnectionsDiscordGuildIdChannelsGet = async (
  guildId: string,
  options?: RequestInit,
): Promise<getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse> => {
  return customFetch<getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse>(
    getGetDiscordChannelsConnectionsDiscordGuildIdChannelsGetUrl(guildId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Delete Connection
 */
export type deleteConnectionConnectionsPlatformDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteConnectionConnectionsPlatformDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteConnectionConnectionsPlatformDeleteResponseSuccess =
  deleteConnectionConnectionsPlatformDeleteResponse200 & {
    headers: Headers;
  };
export type deleteConnectionConnectionsPlatformDeleteResponseError =
  deleteConnectionConnectionsPlatformDeleteResponse422 & {
    headers: Headers;
  };

export type deleteConnectionConnectionsPlatformDeleteResponse =
  | deleteConnectionConnectionsPlatformDeleteResponseSuccess
  | deleteConnectionConnectionsPlatformDeleteResponseError;

export const getDeleteConnectionConnectionsPlatformDeleteUrl = (
  platform: MessagePlatformType,
) => {
  return `/connections/${platform}`;
};

export const deleteConnectionConnectionsPlatformDelete = async (
  platform: MessagePlatformType,
  options?: RequestInit,
): Promise<deleteConnectionConnectionsPlatformDeleteResponse> => {
  return customFetch<deleteConnectionConnectionsPlatformDeleteResponse>(
    getDeleteConnectionConnectionsPlatformDeleteUrl(platform),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List Deployments
 */
export type listDeploymentsDeploymentsGetResponse200 = {
  data: PaginatedResponseDeploymentResponse;
  status: 200;
};

export type listDeploymentsDeploymentsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listDeploymentsDeploymentsGetResponseSuccess =
  listDeploymentsDeploymentsGetResponse200 & {
    headers: Headers;
  };
export type listDeploymentsDeploymentsGetResponseError =
  listDeploymentsDeploymentsGetResponse422 & {
    headers: Headers;
  };

export type listDeploymentsDeploymentsGetResponse =
  | listDeploymentsDeploymentsGetResponseSuccess
  | listDeploymentsDeploymentsGetResponseError;

export const getListDeploymentsDeploymentsGetUrl = (
  params: ListDeploymentsDeploymentsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/deployments/?${stringifiedParams}`
    : `/deployments/`;
};

export const listDeploymentsDeploymentsGet = async (
  bodyListDeploymentsDeploymentsGet: BodyListDeploymentsDeploymentsGet,
  params: ListDeploymentsDeploymentsGetParams,
  options?: RequestInit,
): Promise<listDeploymentsDeploymentsGetResponse> => {
  return customFetch<listDeploymentsDeploymentsGetResponse>(
    getListDeploymentsDeploymentsGetUrl(params),
    {
      ...options,
      method: "GET",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(bodyListDeploymentsDeploymentsGet),
    },
  );
};

/**
 * @summary Get Deployment
 */
export type getDeploymentDeploymentsDeploymentIdGetResponse200 = {
  data: DeploymentResponse;
  status: 200;
};

export type getDeploymentDeploymentsDeploymentIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getDeploymentDeploymentsDeploymentIdGetResponseSuccess =
  getDeploymentDeploymentsDeploymentIdGetResponse200 & {
    headers: Headers;
  };
export type getDeploymentDeploymentsDeploymentIdGetResponseError =
  getDeploymentDeploymentsDeploymentIdGetResponse422 & {
    headers: Headers;
  };

export type getDeploymentDeploymentsDeploymentIdGetResponse =
  | getDeploymentDeploymentsDeploymentIdGetResponseSuccess
  | getDeploymentDeploymentsDeploymentIdGetResponseError;

export const getGetDeploymentDeploymentsDeploymentIdGetUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}`;
};

export const getDeploymentDeploymentsDeploymentIdGet = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<getDeploymentDeploymentsDeploymentIdGetResponse> => {
  return customFetch<getDeploymentDeploymentsDeploymentIdGetResponse>(
    getGetDeploymentDeploymentsDeploymentIdGetUrl(deploymentId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update Deployment
 */
export type updateDeploymentDeploymentsDeploymentIdPutResponse200 = {
  data: DeploymentResponse;
  status: 200;
};

export type updateDeploymentDeploymentsDeploymentIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateDeploymentDeploymentsDeploymentIdPutResponseSuccess =
  updateDeploymentDeploymentsDeploymentIdPutResponse200 & {
    headers: Headers;
  };
export type updateDeploymentDeploymentsDeploymentIdPutResponseError =
  updateDeploymentDeploymentsDeploymentIdPutResponse422 & {
    headers: Headers;
  };

export type updateDeploymentDeploymentsDeploymentIdPutResponse =
  | updateDeploymentDeploymentsDeploymentIdPutResponseSuccess
  | updateDeploymentDeploymentsDeploymentIdPutResponseError;

export const getUpdateDeploymentDeploymentsDeploymentIdPutUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}`;
};

export const updateDeploymentDeploymentsDeploymentIdPut = async (
  deploymentId: string,
  deploymentUpdate: DeploymentUpdate,
  options?: RequestInit,
): Promise<updateDeploymentDeploymentsDeploymentIdPutResponse> => {
  return customFetch<updateDeploymentDeploymentsDeploymentIdPutResponse>(
    getUpdateDeploymentDeploymentsDeploymentIdPutUrl(deploymentId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(deploymentUpdate),
    },
  );
};

/**
 * @summary Delete Deployment
 */
export type deleteDeploymentDeploymentsDeploymentIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteDeploymentDeploymentsDeploymentIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteDeploymentDeploymentsDeploymentIdDeleteResponseSuccess =
  deleteDeploymentDeploymentsDeploymentIdDeleteResponse200 & {
    headers: Headers;
  };
export type deleteDeploymentDeploymentsDeploymentIdDeleteResponseError =
  deleteDeploymentDeploymentsDeploymentIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteDeploymentDeploymentsDeploymentIdDeleteResponse =
  | deleteDeploymentDeploymentsDeploymentIdDeleteResponseSuccess
  | deleteDeploymentDeploymentsDeploymentIdDeleteResponseError;

export const getDeleteDeploymentDeploymentsDeploymentIdDeleteUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}`;
};

export const deleteDeploymentDeploymentsDeploymentIdDelete = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<deleteDeploymentDeploymentsDeploymentIdDeleteResponse> => {
  return customFetch<deleteDeploymentDeploymentsDeploymentIdDeleteResponse>(
    getDeleteDeploymentDeploymentsDeploymentIdDeleteUrl(deploymentId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get Deployment Stats
 */
export type getDeploymentStatsDeploymentsDeploymentIdStatsGetResponse200 = {
  data: DeploymentStats;
  status: 200;
};

export type getDeploymentStatsDeploymentsDeploymentIdStatsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getDeploymentStatsDeploymentsDeploymentIdStatsGetResponseSuccess =
  getDeploymentStatsDeploymentsDeploymentIdStatsGetResponse200 & {
    headers: Headers;
  };
export type getDeploymentStatsDeploymentsDeploymentIdStatsGetResponseError =
  getDeploymentStatsDeploymentsDeploymentIdStatsGetResponse422 & {
    headers: Headers;
  };

export type getDeploymentStatsDeploymentsDeploymentIdStatsGetResponse =
  | getDeploymentStatsDeploymentsDeploymentIdStatsGetResponseSuccess
  | getDeploymentStatsDeploymentsDeploymentIdStatsGetResponseError;

export const getGetDeploymentStatsDeploymentsDeploymentIdStatsGetUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}/stats`;
};

export const getDeploymentStatsDeploymentsDeploymentIdStatsGet = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<getDeploymentStatsDeploymentsDeploymentIdStatsGetResponse> => {
  return customFetch<getDeploymentStatsDeploymentsDeploymentIdStatsGetResponse>(
    getGetDeploymentStatsDeploymentsDeploymentIdStatsGetUrl(deploymentId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Get all actions (ModeratorLogs) for a specific deployment.
Fully type-safe and paginated.
 * @summary Get Deployment Actions
 */
export type getDeploymentActionsDeploymentsDeploymentIdActionsGetResponse200 = {
  data: PaginatedResponseDeploymentAction;
  status: 200;
};

export type getDeploymentActionsDeploymentsDeploymentIdActionsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getDeploymentActionsDeploymentsDeploymentIdActionsGetResponseSuccess =
  getDeploymentActionsDeploymentsDeploymentIdActionsGetResponse200 & {
    headers: Headers;
  };
export type getDeploymentActionsDeploymentsDeploymentIdActionsGetResponseError =
  getDeploymentActionsDeploymentsDeploymentIdActionsGetResponse422 & {
    headers: Headers;
  };

export type getDeploymentActionsDeploymentsDeploymentIdActionsGetResponse =
  | getDeploymentActionsDeploymentsDeploymentIdActionsGetResponseSuccess
  | getDeploymentActionsDeploymentsDeploymentIdActionsGetResponseError;

export const getGetDeploymentActionsDeploymentsDeploymentIdActionsGetUrl = (
  deploymentId: string,
  params?: GetDeploymentActionsDeploymentsDeploymentIdActionsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/deployments/${deploymentId}/actions?${stringifiedParams}`
    : `/deployments/${deploymentId}/actions`;
};

export const getDeploymentActionsDeploymentsDeploymentIdActionsGet = async (
  deploymentId: string,
  params?: GetDeploymentActionsDeploymentsDeploymentIdActionsGetParams,
  options?: RequestInit,
): Promise<getDeploymentActionsDeploymentsDeploymentIdActionsGetResponse> => {
  return customFetch<getDeploymentActionsDeploymentsDeploymentIdActionsGetResponse>(
    getGetDeploymentActionsDeploymentsDeploymentIdActionsGetUrl(
      deploymentId,
      params,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Stop Deployment
 */
export type stopDeploymentDeploymentsDeploymentIdStopPostResponse200 = {
  data: unknown;
  status: 200;
};

export type stopDeploymentDeploymentsDeploymentIdStopPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type stopDeploymentDeploymentsDeploymentIdStopPostResponseSuccess =
  stopDeploymentDeploymentsDeploymentIdStopPostResponse200 & {
    headers: Headers;
  };
export type stopDeploymentDeploymentsDeploymentIdStopPostResponseError =
  stopDeploymentDeploymentsDeploymentIdStopPostResponse422 & {
    headers: Headers;
  };

export type stopDeploymentDeploymentsDeploymentIdStopPostResponse =
  | stopDeploymentDeploymentsDeploymentIdStopPostResponseSuccess
  | stopDeploymentDeploymentsDeploymentIdStopPostResponseError;

export const getStopDeploymentDeploymentsDeploymentIdStopPostUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}/stop`;
};

export const stopDeploymentDeploymentsDeploymentIdStopPost = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<stopDeploymentDeploymentsDeploymentIdStopPostResponse> => {
  return customFetch<stopDeploymentDeploymentsDeploymentIdStopPostResponse>(
    getStopDeploymentDeploymentsDeploymentIdStopPostUrl(deploymentId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Stop Deployment
 */
export type stopDeploymentDeploymentsDeploymentIdStartPostResponse200 = {
  data: unknown;
  status: 200;
};

export type stopDeploymentDeploymentsDeploymentIdStartPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type stopDeploymentDeploymentsDeploymentIdStartPostResponseSuccess =
  stopDeploymentDeploymentsDeploymentIdStartPostResponse200 & {
    headers: Headers;
  };
export type stopDeploymentDeploymentsDeploymentIdStartPostResponseError =
  stopDeploymentDeploymentsDeploymentIdStartPostResponse422 & {
    headers: Headers;
  };

export type stopDeploymentDeploymentsDeploymentIdStartPostResponse =
  | stopDeploymentDeploymentsDeploymentIdStartPostResponseSuccess
  | stopDeploymentDeploymentsDeploymentIdStartPostResponseError;

export const getStopDeploymentDeploymentsDeploymentIdStartPostUrl = (
  deploymentId: string,
) => {
  return `/deployments/${deploymentId}/start`;
};

export const stopDeploymentDeploymentsDeploymentIdStartPost = async (
  deploymentId: string,
  options?: RequestInit,
): Promise<stopDeploymentDeploymentsDeploymentIdStartPostResponse> => {
  return customFetch<stopDeploymentDeploymentsDeploymentIdStartPostResponse>(
    getStopDeploymentDeploymentsDeploymentIdStartPostUrl(deploymentId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Create Guideline
 */
export type createGuidelineGuidelinesPostResponse200 = {
  data: GuidelineResponse;
  status: 200;
};

export type createGuidelineGuidelinesPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createGuidelineGuidelinesPostResponseSuccess =
  createGuidelineGuidelinesPostResponse200 & {
    headers: Headers;
  };
export type createGuidelineGuidelinesPostResponseError =
  createGuidelineGuidelinesPostResponse422 & {
    headers: Headers;
  };

export type createGuidelineGuidelinesPostResponse =
  | createGuidelineGuidelinesPostResponseSuccess
  | createGuidelineGuidelinesPostResponseError;

export const getCreateGuidelineGuidelinesPostUrl = () => {
  return `/guidelines/`;
};

export const createGuidelineGuidelinesPost = async (
  guidelineCreate: GuidelineCreate,
  options?: RequestInit,
): Promise<createGuidelineGuidelinesPostResponse> => {
  return customFetch<createGuidelineGuidelinesPostResponse>(
    getCreateGuidelineGuidelinesPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(guidelineCreate),
    },
  );
};

/**
 * @summary List Guidelines
 */
export type listGuidelinesGuidelinesGetResponse200 = {
  data: PaginatedResponseGuidelineResponse;
  status: 200;
};

export type listGuidelinesGuidelinesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listGuidelinesGuidelinesGetResponseSuccess =
  listGuidelinesGuidelinesGetResponse200 & {
    headers: Headers;
  };
export type listGuidelinesGuidelinesGetResponseError =
  listGuidelinesGuidelinesGetResponse422 & {
    headers: Headers;
  };

export type listGuidelinesGuidelinesGetResponse =
  | listGuidelinesGuidelinesGetResponseSuccess
  | listGuidelinesGuidelinesGetResponseError;

export const getListGuidelinesGuidelinesGetUrl = (
  params: ListGuidelinesGuidelinesGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/guidelines/?${stringifiedParams}`
    : `/guidelines/`;
};

export const listGuidelinesGuidelinesGet = async (
  params: ListGuidelinesGuidelinesGetParams,
  options?: RequestInit,
): Promise<listGuidelinesGuidelinesGetResponse> => {
  return customFetch<listGuidelinesGuidelinesGetResponse>(
    getListGuidelinesGuidelinesGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Guideline
 */
export type getGuidelineGuidelinesGuidelineIdGetResponse200 = {
  data: GuidelineResponse;
  status: 200;
};

export type getGuidelineGuidelinesGuidelineIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getGuidelineGuidelinesGuidelineIdGetResponseSuccess =
  getGuidelineGuidelinesGuidelineIdGetResponse200 & {
    headers: Headers;
  };
export type getGuidelineGuidelinesGuidelineIdGetResponseError =
  getGuidelineGuidelinesGuidelineIdGetResponse422 & {
    headers: Headers;
  };

export type getGuidelineGuidelinesGuidelineIdGetResponse =
  | getGuidelineGuidelinesGuidelineIdGetResponseSuccess
  | getGuidelineGuidelinesGuidelineIdGetResponseError;

export const getGetGuidelineGuidelinesGuidelineIdGetUrl = (
  guidelineId: string,
) => {
  return `/guidelines/${guidelineId}`;
};

export const getGuidelineGuidelinesGuidelineIdGet = async (
  guidelineId: string,
  options?: RequestInit,
): Promise<getGuidelineGuidelinesGuidelineIdGetResponse> => {
  return customFetch<getGuidelineGuidelinesGuidelineIdGetResponse>(
    getGetGuidelineGuidelinesGuidelineIdGetUrl(guidelineId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update Guideline
 */
export type updateGuidelineGuidelinesGuidelineIdPutResponse200 = {
  data: GuidelineResponse;
  status: 200;
};

export type updateGuidelineGuidelinesGuidelineIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateGuidelineGuidelinesGuidelineIdPutResponseSuccess =
  updateGuidelineGuidelinesGuidelineIdPutResponse200 & {
    headers: Headers;
  };
export type updateGuidelineGuidelinesGuidelineIdPutResponseError =
  updateGuidelineGuidelinesGuidelineIdPutResponse422 & {
    headers: Headers;
  };

export type updateGuidelineGuidelinesGuidelineIdPutResponse =
  | updateGuidelineGuidelinesGuidelineIdPutResponseSuccess
  | updateGuidelineGuidelinesGuidelineIdPutResponseError;

export const getUpdateGuidelineGuidelinesGuidelineIdPutUrl = (
  guidelineId: string,
) => {
  return `/guidelines/${guidelineId}`;
};

export const updateGuidelineGuidelinesGuidelineIdPut = async (
  guidelineId: string,
  guidelineUpdate: GuidelineUpdate,
  options?: RequestInit,
): Promise<updateGuidelineGuidelinesGuidelineIdPutResponse> => {
  return customFetch<updateGuidelineGuidelinesGuidelineIdPutResponse>(
    getUpdateGuidelineGuidelinesGuidelineIdPutUrl(guidelineId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(guidelineUpdate),
    },
  );
};

/**
 * @summary Delete Guideline
 */
export type deleteGuidelineGuidelinesGuidelineIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteGuidelineGuidelinesGuidelineIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteGuidelineGuidelinesGuidelineIdDeleteResponseSuccess =
  deleteGuidelineGuidelinesGuidelineIdDeleteResponse200 & {
    headers: Headers;
  };
export type deleteGuidelineGuidelinesGuidelineIdDeleteResponseError =
  deleteGuidelineGuidelinesGuidelineIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteGuidelineGuidelinesGuidelineIdDeleteResponse =
  | deleteGuidelineGuidelinesGuidelineIdDeleteResponseSuccess
  | deleteGuidelineGuidelinesGuidelineIdDeleteResponseError;

export const getDeleteGuidelineGuidelinesGuidelineIdDeleteUrl = (
  guidelineId: string,
) => {
  return `/guidelines/${guidelineId}`;
};

export const deleteGuidelineGuidelinesGuidelineIdDelete = async (
  guidelineId: string,
  options?: RequestInit,
): Promise<deleteGuidelineGuidelinesGuidelineIdDeleteResponse> => {
  return customFetch<deleteGuidelineGuidelinesGuidelineIdDeleteResponse>(
    getDeleteGuidelineGuidelinesGuidelineIdDeleteUrl(guidelineId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Create Moderator
 */
export type createModeratorModeratorsPostResponse200 = {
  data: ModeratorResponse;
  status: 200;
};

export type createModeratorModeratorsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createModeratorModeratorsPostResponseSuccess =
  createModeratorModeratorsPostResponse200 & {
    headers: Headers;
  };
export type createModeratorModeratorsPostResponseError =
  createModeratorModeratorsPostResponse422 & {
    headers: Headers;
  };

export type createModeratorModeratorsPostResponse =
  | createModeratorModeratorsPostResponseSuccess
  | createModeratorModeratorsPostResponseError;

export const getCreateModeratorModeratorsPostUrl = () => {
  return `/moderators/`;
};

export const createModeratorModeratorsPost = async (
  moderatorCreate: ModeratorCreate,
  options?: RequestInit,
): Promise<createModeratorModeratorsPostResponse> => {
  return customFetch<createModeratorModeratorsPostResponse>(
    getCreateModeratorModeratorsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(moderatorCreate),
    },
  );
};

/**
 * @summary List Moderators
 */
export type listModeratorsModeratorsGetResponse200 = {
  data: PaginatedResponseModeratorResponse;
  status: 200;
};

export type listModeratorsModeratorsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listModeratorsModeratorsGetResponseSuccess =
  listModeratorsModeratorsGetResponse200 & {
    headers: Headers;
  };
export type listModeratorsModeratorsGetResponseError =
  listModeratorsModeratorsGetResponse422 & {
    headers: Headers;
  };

export type listModeratorsModeratorsGetResponse =
  | listModeratorsModeratorsGetResponseSuccess
  | listModeratorsModeratorsGetResponseError;

export const getListModeratorsModeratorsGetUrl = (
  params: ListModeratorsModeratorsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/moderators/?${stringifiedParams}`
    : `/moderators/`;
};

export const listModeratorsModeratorsGet = async (
  params: ListModeratorsModeratorsGetParams,
  options?: RequestInit,
): Promise<listModeratorsModeratorsGetResponse> => {
  return customFetch<listModeratorsModeratorsGetResponse>(
    getListModeratorsModeratorsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Deploy Moderator
 */
export type deployModeratorModeratorsModeratorIdDeployPostResponse200 = {
  data: DeploymentResponse;
  status: 200;
};

export type deployModeratorModeratorsModeratorIdDeployPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deployModeratorModeratorsModeratorIdDeployPostResponseSuccess =
  deployModeratorModeratorsModeratorIdDeployPostResponse200 & {
    headers: Headers;
  };
export type deployModeratorModeratorsModeratorIdDeployPostResponseError =
  deployModeratorModeratorsModeratorIdDeployPostResponse422 & {
    headers: Headers;
  };

export type deployModeratorModeratorsModeratorIdDeployPostResponse =
  | deployModeratorModeratorsModeratorIdDeployPostResponseSuccess
  | deployModeratorModeratorsModeratorIdDeployPostResponseError;

export const getDeployModeratorModeratorsModeratorIdDeployPostUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}/deploy`;
};

export const deployModeratorModeratorsModeratorIdDeployPost = async (
  moderatorId: string,
  deploymentCreate: DeploymentCreate,
  options?: RequestInit,
): Promise<deployModeratorModeratorsModeratorIdDeployPostResponse> => {
  return customFetch<deployModeratorModeratorsModeratorIdDeployPostResponse>(
    getDeployModeratorModeratorsModeratorIdDeployPostUrl(moderatorId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(deploymentCreate),
    },
  );
};

/**
 * @summary Get Moderator
 */
export type getModeratorModeratorsModeratorIdGetResponse200 = {
  data: ModeratorResponse;
  status: 200;
};

export type getModeratorModeratorsModeratorIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getModeratorModeratorsModeratorIdGetResponseSuccess =
  getModeratorModeratorsModeratorIdGetResponse200 & {
    headers: Headers;
  };
export type getModeratorModeratorsModeratorIdGetResponseError =
  getModeratorModeratorsModeratorIdGetResponse422 & {
    headers: Headers;
  };

export type getModeratorModeratorsModeratorIdGetResponse =
  | getModeratorModeratorsModeratorIdGetResponseSuccess
  | getModeratorModeratorsModeratorIdGetResponseError;

export const getGetModeratorModeratorsModeratorIdGetUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const getModeratorModeratorsModeratorIdGet = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<getModeratorModeratorsModeratorIdGetResponse> => {
  return customFetch<getModeratorModeratorsModeratorIdGetResponse>(
    getGetModeratorModeratorsModeratorIdGetUrl(moderatorId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update Moderator
 */
export type updateModeratorModeratorsModeratorIdPutResponse200 = {
  data: ModeratorResponse;
  status: 200;
};

export type updateModeratorModeratorsModeratorIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateModeratorModeratorsModeratorIdPutResponseSuccess =
  updateModeratorModeratorsModeratorIdPutResponse200 & {
    headers: Headers;
  };
export type updateModeratorModeratorsModeratorIdPutResponseError =
  updateModeratorModeratorsModeratorIdPutResponse422 & {
    headers: Headers;
  };

export type updateModeratorModeratorsModeratorIdPutResponse =
  | updateModeratorModeratorsModeratorIdPutResponseSuccess
  | updateModeratorModeratorsModeratorIdPutResponseError;

export const getUpdateModeratorModeratorsModeratorIdPutUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const updateModeratorModeratorsModeratorIdPut = async (
  moderatorId: string,
  moderatorUpdate: ModeratorUpdate,
  options?: RequestInit,
): Promise<updateModeratorModeratorsModeratorIdPutResponse> => {
  return customFetch<updateModeratorModeratorsModeratorIdPutResponse>(
    getUpdateModeratorModeratorsModeratorIdPutUrl(moderatorId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(moderatorUpdate),
    },
  );
};

/**
 * @summary Delete Moderator
 */
export type deleteModeratorModeratorsModeratorIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteModeratorModeratorsModeratorIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteModeratorModeratorsModeratorIdDeleteResponseSuccess =
  deleteModeratorModeratorsModeratorIdDeleteResponse200 & {
    headers: Headers;
  };
export type deleteModeratorModeratorsModeratorIdDeleteResponseError =
  deleteModeratorModeratorsModeratorIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteModeratorModeratorsModeratorIdDeleteResponse =
  | deleteModeratorModeratorsModeratorIdDeleteResponseSuccess
  | deleteModeratorModeratorsModeratorIdDeleteResponseError;

export const getDeleteModeratorModeratorsModeratorIdDeleteUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const deleteModeratorModeratorsModeratorIdDelete = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<deleteModeratorModeratorsModeratorIdDeleteResponse> => {
  return customFetch<deleteModeratorModeratorsModeratorIdDeleteResponse>(
    getDeleteModeratorModeratorsModeratorIdDeleteUrl(moderatorId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get Deployments
 */
export type getDeploymentsModeratorsModeratorIdDeploymentsGetResponse200 = {
  data: PaginatedResponseDeploymentResponse;
  status: 200;
};

export type getDeploymentsModeratorsModeratorIdDeploymentsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getDeploymentsModeratorsModeratorIdDeploymentsGetResponseSuccess =
  getDeploymentsModeratorsModeratorIdDeploymentsGetResponse200 & {
    headers: Headers;
  };
export type getDeploymentsModeratorsModeratorIdDeploymentsGetResponseError =
  getDeploymentsModeratorsModeratorIdDeploymentsGetResponse422 & {
    headers: Headers;
  };

export type getDeploymentsModeratorsModeratorIdDeploymentsGetResponse =
  | getDeploymentsModeratorsModeratorIdDeploymentsGetResponseSuccess
  | getDeploymentsModeratorsModeratorIdDeploymentsGetResponseError;

export const getGetDeploymentsModeratorsModeratorIdDeploymentsGetUrl = (
  moderatorId: string,
  params?: GetDeploymentsModeratorsModeratorIdDeploymentsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/moderators/${moderatorId}/deployments?${stringifiedParams}`
    : `/moderators/${moderatorId}/deployments`;
};

export const getDeploymentsModeratorsModeratorIdDeploymentsGet = async (
  moderatorId: string,
  params?: GetDeploymentsModeratorsModeratorIdDeploymentsGetParams,
  options?: RequestInit,
): Promise<getDeploymentsModeratorsModeratorIdDeploymentsGetResponse> => {
  return customFetch<getDeploymentsModeratorsModeratorIdDeploymentsGetResponse>(
    getGetDeploymentsModeratorsModeratorIdDeploymentsGetUrl(
      moderatorId,
      params,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Moderator Stats
 */
export type getModeratorStatsModeratorsModeratorIdStatsGetResponse200 = {
  data: ModeratorStats;
  status: 200;
};

export type getModeratorStatsModeratorsModeratorIdStatsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getModeratorStatsModeratorsModeratorIdStatsGetResponseSuccess =
  getModeratorStatsModeratorsModeratorIdStatsGetResponse200 & {
    headers: Headers;
  };
export type getModeratorStatsModeratorsModeratorIdStatsGetResponseError =
  getModeratorStatsModeratorsModeratorIdStatsGetResponse422 & {
    headers: Headers;
  };

export type getModeratorStatsModeratorsModeratorIdStatsGetResponse =
  | getModeratorStatsModeratorsModeratorIdStatsGetResponseSuccess
  | getModeratorStatsModeratorsModeratorIdStatsGetResponseError;

export const getGetModeratorStatsModeratorsModeratorIdStatsGetUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}/stats`;
};

export const getModeratorStatsModeratorsModeratorIdStatsGet = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<getModeratorStatsModeratorsModeratorIdStatsGetResponse> => {
  return customFetch<getModeratorStatsModeratorsModeratorIdStatsGetResponse>(
    getGetModeratorStatsModeratorsModeratorIdStatsGetUrl(moderatorId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Generate a Stripe Checkout link for a given user and pricing tier.
 * @summary Get Payment Link
 */
export type getPaymentLinkPaymentsPaymentLinkGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getPaymentLinkPaymentsPaymentLinkGetResponseSuccess =
  getPaymentLinkPaymentsPaymentLinkGetResponse200 & {
    headers: Headers;
  };
export type getPaymentLinkPaymentsPaymentLinkGetResponse =
  getPaymentLinkPaymentsPaymentLinkGetResponseSuccess;

export const getGetPaymentLinkPaymentsPaymentLinkGetUrl = () => {
  return `/payments/payment-link`;
};

export const getPaymentLinkPaymentsPaymentLinkGet = async (
  options?: RequestInit,
): Promise<getPaymentLinkPaymentsPaymentLinkGetResponse> => {
  return customFetch<getPaymentLinkPaymentsPaymentLinkGetResponse>(
    getGetPaymentLinkPaymentsPaymentLinkGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Stripe webhook endpoint for handling subscription events.
 * @summary Stripe Webhook
 */
export type stripeWebhookPaymentsStripeWebhookPostResponse200 = {
  data: unknown;
  status: 200;
};

export type stripeWebhookPaymentsStripeWebhookPostResponseSuccess =
  stripeWebhookPaymentsStripeWebhookPostResponse200 & {
    headers: Headers;
  };
export type stripeWebhookPaymentsStripeWebhookPostResponse =
  stripeWebhookPaymentsStripeWebhookPostResponseSuccess;

export const getStripeWebhookPaymentsStripeWebhookPostUrl = () => {
  return `/payments/stripe/webhook`;
};

export const stripeWebhookPaymentsStripeWebhookPost = async (
  options?: RequestInit,
): Promise<stripeWebhookPaymentsStripeWebhookPostResponse> => {
  return customFetch<stripeWebhookPaymentsStripeWebhookPostResponse>(
    getStripeWebhookPaymentsStripeWebhookPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Contact Us
 */
export type contactUsPublicContactUsPostResponse202 = {
  data: unknown;
  status: 202;
};

export type contactUsPublicContactUsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type contactUsPublicContactUsPostResponseSuccess =
  contactUsPublicContactUsPostResponse202 & {
    headers: Headers;
  };
export type contactUsPublicContactUsPostResponseError =
  contactUsPublicContactUsPostResponse422 & {
    headers: Headers;
  };

export type contactUsPublicContactUsPostResponse =
  | contactUsPublicContactUsPostResponseSuccess
  | contactUsPublicContactUsPostResponseError;

export const getContactUsPublicContactUsPostUrl = () => {
  return `/public/contact-us`;
};

export const contactUsPublicContactUsPost = async (
  contactForm: ContactForm,
  options?: RequestInit,
): Promise<contactUsPublicContactUsPostResponse> => {
  return customFetch<contactUsPublicContactUsPostResponse>(
    getContactUsPublicContactUsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(contactForm),
    },
  );
};
