/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from "./lib/custom-fetch";
export type ActionResponsePlatformUserId = string | null;

export type ActionResponseActionParamsAnyOf = { [key: string]: unknown };

export type ActionResponseActionParams = ActionResponseActionParamsAnyOf | null;

export type ActionResponseContext = { [key: string]: unknown };

export type ActionResponseReason = string | null;

export type ActionResponseExecutedAt = string | null;

/**
 * Response model for action data.
 */
export interface ActionResponse {
  action_id: string;
  moderator_id: string;
  platform_user_id: ActionResponsePlatformUserId;
  action_type: string;
  action_params: ActionResponseActionParams;
  context: ActionResponseContext;
  status: ActionStatus;
  reason: ActionResponseReason;
  created_at: string;
  updated_at: string;
  executed_at: ActionResponseExecutedAt;
}

export type ActionStatus = (typeof ActionStatus)[keyof typeof ActionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionStatus = {
  completed: "completed",
  awaiting_approval: "awaiting_approval",
  failed: "failed",
  rejected: "rejected",
} as const;

/**
 * Bar chart data point for stats.
 */
export interface BarChartData {
  date: string;
  evaluations_count: number;
  actions_count: number;
}

/**
 * Response model for user behavior score.
 */
export interface BehaviorScoreResponse {
  user_id: string;
  username: string;
  behaviour_score: number;
}

export interface ContactForm {
  name: string;
  email: string;
  message: string;
}

export type GuildIcon = string | null;

export interface Guild {
  id: string;
  name: string;
  icon: GuildIcon;
}

export interface GuildChannel {
  id: string;
  name: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type MessagePlatform =
  (typeof MessagePlatform)[keyof typeof MessagePlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessagePlatform = {
  discord: "discord",
} as const;

export type ModeratorCreateDescription = string | null;

export type ModeratorCreateConf = { [key: string]: unknown };

/**
 * Request model for creating a new moderator.
 */
export interface ModeratorCreate {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  description?: ModeratorCreateDescription;
  platform: MessagePlatform;
  platform_server_id: string;
  conf: ModeratorCreateConf;
}

export type ModeratorResponseDescription = string | null;

export type ModeratorResponseConf = { [key: string]: unknown };

/**
 * Response model for moderator data.
 */
export interface ModeratorResponse {
  moderator_id: string;
  name: string;
  description: ModeratorResponseDescription;
  platform: MessagePlatform;
  platform_server_id: string;
  conf: ModeratorResponseConf;
  status: ModeratorStatus;
  created_at: string;
}

/**
 * Stats response for a moderator.
 */
export interface ModeratorStats {
  evaluations_count: number;
  actions_count: number;
  bar_chart: BarChartData[];
}

export type ModeratorStatus =
  (typeof ModeratorStatus)[keyof typeof ModeratorStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModeratorStatus = {
  offline: "offline",
  pending: "pending",
  online: "online",
} as const;

export type ModeratorUpdateName = string | null;

export type ModeratorUpdateDescription = string | null;

export type ModeratorUpdateConfAnyOf = { [key: string]: unknown };

export type ModeratorUpdateConf = ModeratorUpdateConfAnyOf | null;

/**
 * Request model for updating a moderator.
 */
export interface ModeratorUpdate {
  name?: ModeratorUpdateName;
  description?: ModeratorUpdateDescription;
  conf?: ModeratorUpdateConf;
}

export interface PaginatedResponseActionResponse {
  page: number;
  size: number;
  has_next: boolean;
  data: ActionResponse[];
}

export interface PaginatedResponseBehaviorScoreResponse {
  page: number;
  size: number;
  has_next: boolean;
  data: BehaviorScoreResponse[];
}

export interface PaginatedResponseModeratorResponse {
  page: number;
  size: number;
  has_next: boolean;
  data: ModeratorResponse[];
}

export type PricingTier = (typeof PricingTier)[keyof typeof PricingTier];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PricingTier = {
  free: "free",
  pro: "pro",
} as const;

export interface UpdatePassword {
  password: string;
}

export interface UpdateUsername {
  username: string;
}

export interface UserConnection {
  username: string;
  avatar: string;
}

export interface UserCreate {
  password: string;
  username: string;
  email: string;
}

export type UserLoginUsername = string | null;

export type UserLoginEmail = string | null;

export interface UserLogin {
  username?: UserLoginUsername;
  email?: UserLoginEmail;
  password: string;
}

export type UserMeConnections = { [key: string]: UserConnection };

export interface UserMe {
  username: string;
  pricing_tier: PricingTier;
  connections: UserMeConnections;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type VerifyActionAction =
  (typeof VerifyActionAction)[keyof typeof VerifyActionAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyActionAction = {
  change_username: "change_username",
  change_password: "change_password",
} as const;

export interface VerifyAction {
  code: string;
  action: VerifyActionAction;
}

export interface VerifyCode {
  code: string;
}

export type DiscordOauthCallbackAuthDiscordOauthGetParams = {
  code: string;
};

export type DiscordOauthBotCallbackAuthDiscordOauthBotGetParams = {
  code: string;
};

export type ListModeratorsModeratorsGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  name?: string | null;
};

export type GetModeratorStatsModeratorsModeratorIdStatsGetParams = {
  timeframe?: GetModeratorStatsModeratorsModeratorIdStatsGetTimeframe;
};

export type GetModeratorStatsModeratorsModeratorIdStatsGetTimeframe =
  (typeof GetModeratorStatsModeratorsModeratorIdStatsGetTimeframe)[keyof typeof GetModeratorStatsModeratorsModeratorIdStatsGetTimeframe];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetModeratorStatsModeratorsModeratorIdStatsGetTimeframe = {
  "1w": "1w",
  "1m": "1m",
  "1y": "1y",
} as const;

export type ListModeratorActionsModeratorsModeratorIdActionsGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type ListBehaviorScoresModeratorsModeratorIdScoresGetParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  order?: "asc" | "desc" | null;
};

/**
 * Approve and execute an action that is awaiting approval.
 * @summary Approve Action
 */
export type approveActionActionsActionIdApprovePostResponse200 = {
  data: ActionResponse;
  status: 200;
};

export type approveActionActionsActionIdApprovePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type approveActionActionsActionIdApprovePostResponseSuccess =
  approveActionActionsActionIdApprovePostResponse200 & {
    headers: Headers;
  };
export type approveActionActionsActionIdApprovePostResponseError =
  approveActionActionsActionIdApprovePostResponse422 & {
    headers: Headers;
  };

export type approveActionActionsActionIdApprovePostResponse =
  | approveActionActionsActionIdApprovePostResponseSuccess
  | approveActionActionsActionIdApprovePostResponseError;

export const getApproveActionActionsActionIdApprovePostUrl = (
  actionId: string,
) => {
  return `/actions/${actionId}/approve`;
};

export const approveActionActionsActionIdApprovePost = async (
  actionId: string,
  options?: RequestInit,
): Promise<approveActionActionsActionIdApprovePostResponse> => {
  return customFetch<approveActionActionsActionIdApprovePostResponse>(
    getApproveActionActionsActionIdApprovePostUrl(actionId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * Reject an action that is awaiting approval.
 * @summary Reject Action
 */
export type rejectActionActionsActionIdRejectPostResponse200 = {
  data: ActionResponse;
  status: 200;
};

export type rejectActionActionsActionIdRejectPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type rejectActionActionsActionIdRejectPostResponseSuccess =
  rejectActionActionsActionIdRejectPostResponse200 & {
    headers: Headers;
  };
export type rejectActionActionsActionIdRejectPostResponseError =
  rejectActionActionsActionIdRejectPostResponse422 & {
    headers: Headers;
  };

export type rejectActionActionsActionIdRejectPostResponse =
  | rejectActionActionsActionIdRejectPostResponseSuccess
  | rejectActionActionsActionIdRejectPostResponseError;

export const getRejectActionActionsActionIdRejectPostUrl = (
  actionId: string,
) => {
  return `/actions/${actionId}/reject`;
};

export const rejectActionActionsActionIdRejectPost = async (
  actionId: string,
  options?: RequestInit,
): Promise<rejectActionActionsActionIdRejectPostResponse> => {
  return customFetch<rejectActionActionsActionIdRejectPostResponse>(
    getRejectActionActionsActionIdRejectPostUrl(actionId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Register
 */
export type registerAuthRegisterPostResponse200 = {
  data: unknown;
  status: 200;
};

export type registerAuthRegisterPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type registerAuthRegisterPostResponseSuccess =
  registerAuthRegisterPostResponse200 & {
    headers: Headers;
  };
export type registerAuthRegisterPostResponseError =
  registerAuthRegisterPostResponse422 & {
    headers: Headers;
  };

export type registerAuthRegisterPostResponse =
  | registerAuthRegisterPostResponseSuccess
  | registerAuthRegisterPostResponseError;

export const getRegisterAuthRegisterPostUrl = () => {
  return `/auth/register`;
};

export const registerAuthRegisterPost = async (
  userCreate: UserCreate,
  options?: RequestInit,
): Promise<registerAuthRegisterPostResponse> => {
  return customFetch<registerAuthRegisterPostResponse>(
    getRegisterAuthRegisterPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userCreate),
    },
  );
};

/**
 * @summary Login
 */
export type loginAuthLoginPostResponse200 = {
  data: unknown;
  status: 200;
};

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginAuthLoginPostResponseSuccess =
  loginAuthLoginPostResponse200 & {
    headers: Headers;
  };
export type loginAuthLoginPostResponseError = loginAuthLoginPostResponse422 & {
  headers: Headers;
};

export type loginAuthLoginPostResponse =
  | loginAuthLoginPostResponseSuccess
  | loginAuthLoginPostResponseError;

export const getLoginAuthLoginPostUrl = () => {
  return `/auth/login`;
};

export const loginAuthLoginPost = async (
  userLogin: UserLogin,
  options?: RequestInit,
): Promise<loginAuthLoginPostResponse> => {
  return customFetch<loginAuthLoginPostResponse>(getLoginAuthLoginPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userLogin),
  });
};

/**
 * @summary Request Email Verification
 */
export type requestEmailVerificationAuthRequestEmailVerificationPostResponse200 =
  {
    data: unknown;
    status: 200;
  };

export type requestEmailVerificationAuthRequestEmailVerificationPostResponseSuccess =
  requestEmailVerificationAuthRequestEmailVerificationPostResponse200 & {
    headers: Headers;
  };
export type requestEmailVerificationAuthRequestEmailVerificationPostResponse =
  requestEmailVerificationAuthRequestEmailVerificationPostResponseSuccess;

export const getRequestEmailVerificationAuthRequestEmailVerificationPostUrl =
  () => {
    return `/auth/request-email-verification`;
  };

export const requestEmailVerificationAuthRequestEmailVerificationPost = async (
  options?: RequestInit,
): Promise<requestEmailVerificationAuthRequestEmailVerificationPostResponse> => {
  return customFetch<requestEmailVerificationAuthRequestEmailVerificationPostResponse>(
    getRequestEmailVerificationAuthRequestEmailVerificationPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Verify Email
 */
export type verifyEmailAuthVerifyEmailPostResponse200 = {
  data: unknown;
  status: 200;
};

export type verifyEmailAuthVerifyEmailPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type verifyEmailAuthVerifyEmailPostResponseSuccess =
  verifyEmailAuthVerifyEmailPostResponse200 & {
    headers: Headers;
  };
export type verifyEmailAuthVerifyEmailPostResponseError =
  verifyEmailAuthVerifyEmailPostResponse422 & {
    headers: Headers;
  };

export type verifyEmailAuthVerifyEmailPostResponse =
  | verifyEmailAuthVerifyEmailPostResponseSuccess
  | verifyEmailAuthVerifyEmailPostResponseError;

export const getVerifyEmailAuthVerifyEmailPostUrl = () => {
  return `/auth/verify-email`;
};

export const verifyEmailAuthVerifyEmailPost = async (
  verifyCode: VerifyCode,
  options?: RequestInit,
): Promise<verifyEmailAuthVerifyEmailPostResponse> => {
  return customFetch<verifyEmailAuthVerifyEmailPostResponse>(
    getVerifyEmailAuthVerifyEmailPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(verifyCode),
    },
  );
};

/**
 * @summary Logout
 */
export type logoutAuthLogoutPostResponse200 = {
  data: unknown;
  status: 200;
};

export type logoutAuthLogoutPostResponseSuccess =
  logoutAuthLogoutPostResponse200 & {
    headers: Headers;
  };
export type logoutAuthLogoutPostResponse = logoutAuthLogoutPostResponseSuccess;

export const getLogoutAuthLogoutPostUrl = () => {
  return `/auth/logout`;
};

export const logoutAuthLogoutPost = async (
  options?: RequestInit,
): Promise<logoutAuthLogoutPostResponse> => {
  return customFetch<logoutAuthLogoutPostResponse>(
    getLogoutAuthLogoutPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Get Me
 */
export type getMeAuthMeGetResponse200 = {
  data: UserMe;
  status: 200;
};

export type getMeAuthMeGetResponseSuccess = getMeAuthMeGetResponse200 & {
  headers: Headers;
};
export type getMeAuthMeGetResponse = getMeAuthMeGetResponseSuccess;

export const getGetMeAuthMeGetUrl = () => {
  return `/auth/me`;
};

export const getMeAuthMeGet = async (
  options?: RequestInit,
): Promise<getMeAuthMeGetResponse> => {
  return customFetch<getMeAuthMeGetResponse>(getGetMeAuthMeGetUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Discord Oauth Callback
 */
export type discordOauthCallbackAuthDiscordOauthGetResponse200 = {
  data: unknown;
  status: 200;
};

export type discordOauthCallbackAuthDiscordOauthGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type discordOauthCallbackAuthDiscordOauthGetResponseSuccess =
  discordOauthCallbackAuthDiscordOauthGetResponse200 & {
    headers: Headers;
  };
export type discordOauthCallbackAuthDiscordOauthGetResponseError =
  discordOauthCallbackAuthDiscordOauthGetResponse422 & {
    headers: Headers;
  };

export type discordOauthCallbackAuthDiscordOauthGetResponse =
  | discordOauthCallbackAuthDiscordOauthGetResponseSuccess
  | discordOauthCallbackAuthDiscordOauthGetResponseError;

export const getDiscordOauthCallbackAuthDiscordOauthGetUrl = (
  params: DiscordOauthCallbackAuthDiscordOauthGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/discord/oauth?${stringifiedParams}`
    : `/auth/discord/oauth`;
};

export const discordOauthCallbackAuthDiscordOauthGet = async (
  params: DiscordOauthCallbackAuthDiscordOauthGetParams,
  options?: RequestInit,
): Promise<discordOauthCallbackAuthDiscordOauthGetResponse> => {
  return customFetch<discordOauthCallbackAuthDiscordOauthGetResponse>(
    getDiscordOauthCallbackAuthDiscordOauthGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Handle Discord bot OAuth callback to add bot to guild.
 * @summary Discord Oauth Bot Callback
 */
export type discordOauthBotCallbackAuthDiscordOauthBotGetResponse200 = {
  data: unknown;
  status: 200;
};

export type discordOauthBotCallbackAuthDiscordOauthBotGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type discordOauthBotCallbackAuthDiscordOauthBotGetResponseSuccess =
  discordOauthBotCallbackAuthDiscordOauthBotGetResponse200 & {
    headers: Headers;
  };
export type discordOauthBotCallbackAuthDiscordOauthBotGetResponseError =
  discordOauthBotCallbackAuthDiscordOauthBotGetResponse422 & {
    headers: Headers;
  };

export type discordOauthBotCallbackAuthDiscordOauthBotGetResponse =
  | discordOauthBotCallbackAuthDiscordOauthBotGetResponseSuccess
  | discordOauthBotCallbackAuthDiscordOauthBotGetResponseError;

export const getDiscordOauthBotCallbackAuthDiscordOauthBotGetUrl = (
  params: DiscordOauthBotCallbackAuthDiscordOauthBotGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/discord/oauth/bot?${stringifiedParams}`
    : `/auth/discord/oauth/bot`;
};

export const discordOauthBotCallbackAuthDiscordOauthBotGet = async (
  params: DiscordOauthBotCallbackAuthDiscordOauthBotGetParams,
  options?: RequestInit,
): Promise<discordOauthBotCallbackAuthDiscordOauthBotGetResponse> => {
  return customFetch<discordOauthBotCallbackAuthDiscordOauthBotGetResponse>(
    getDiscordOauthBotCallbackAuthDiscordOauthBotGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Change Username
 */
export type changeUsernameAuthChangeUsernamePostResponse202 = {
  data: unknown;
  status: 202;
};

export type changeUsernameAuthChangeUsernamePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type changeUsernameAuthChangeUsernamePostResponseSuccess =
  changeUsernameAuthChangeUsernamePostResponse202 & {
    headers: Headers;
  };
export type changeUsernameAuthChangeUsernamePostResponseError =
  changeUsernameAuthChangeUsernamePostResponse422 & {
    headers: Headers;
  };

export type changeUsernameAuthChangeUsernamePostResponse =
  | changeUsernameAuthChangeUsernamePostResponseSuccess
  | changeUsernameAuthChangeUsernamePostResponseError;

export const getChangeUsernameAuthChangeUsernamePostUrl = () => {
  return `/auth/change-username`;
};

export const changeUsernameAuthChangeUsernamePost = async (
  updateUsername: UpdateUsername,
  options?: RequestInit,
): Promise<changeUsernameAuthChangeUsernamePostResponse> => {
  return customFetch<changeUsernameAuthChangeUsernamePostResponse>(
    getChangeUsernameAuthChangeUsernamePostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateUsername),
    },
  );
};

/**
 * @summary Change Password
 */
export type changePasswordAuthChangePasswordPostResponse202 = {
  data: unknown;
  status: 202;
};

export type changePasswordAuthChangePasswordPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type changePasswordAuthChangePasswordPostResponseSuccess =
  changePasswordAuthChangePasswordPostResponse202 & {
    headers: Headers;
  };
export type changePasswordAuthChangePasswordPostResponseError =
  changePasswordAuthChangePasswordPostResponse422 & {
    headers: Headers;
  };

export type changePasswordAuthChangePasswordPostResponse =
  | changePasswordAuthChangePasswordPostResponseSuccess
  | changePasswordAuthChangePasswordPostResponseError;

export const getChangePasswordAuthChangePasswordPostUrl = () => {
  return `/auth/change-password`;
};

export const changePasswordAuthChangePasswordPost = async (
  updatePassword: UpdatePassword,
  options?: RequestInit,
): Promise<changePasswordAuthChangePasswordPostResponse> => {
  return customFetch<changePasswordAuthChangePasswordPostResponse>(
    getChangePasswordAuthChangePasswordPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updatePassword),
    },
  );
};

/**
 * @summary Verify Action
 */
export type verifyActionAuthVerifyActionPostResponse200 = {
  data: unknown;
  status: 200;
};

export type verifyActionAuthVerifyActionPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type verifyActionAuthVerifyActionPostResponseSuccess =
  verifyActionAuthVerifyActionPostResponse200 & {
    headers: Headers;
  };
export type verifyActionAuthVerifyActionPostResponseError =
  verifyActionAuthVerifyActionPostResponse422 & {
    headers: Headers;
  };

export type verifyActionAuthVerifyActionPostResponse =
  | verifyActionAuthVerifyActionPostResponseSuccess
  | verifyActionAuthVerifyActionPostResponseError;

export const getVerifyActionAuthVerifyActionPostUrl = () => {
  return `/auth/verify-action`;
};

export const verifyActionAuthVerifyActionPost = async (
  verifyAction: VerifyAction,
  options?: RequestInit,
): Promise<verifyActionAuthVerifyActionPostResponse> => {
  return customFetch<verifyActionAuthVerifyActionPostResponse>(
    getVerifyActionAuthVerifyActionPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(verifyAction),
    },
  );
};

/**
 * @summary Get Owned Discord Guilds
 */
export type getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse200 = {
  data: Guild[];
  status: 200;
};

export type getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponseSuccess =
  getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse200 & {
    headers: Headers;
  };
export type getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse =
  getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponseSuccess;

export const getGetOwnedDiscordGuildsConnectionsDiscordGuildsGetUrl = () => {
  return `/connections/discord/guilds`;
};

export const getOwnedDiscordGuildsConnectionsDiscordGuildsGet = async (
  options?: RequestInit,
): Promise<getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse> => {
  return customFetch<getOwnedDiscordGuildsConnectionsDiscordGuildsGetResponse>(
    getGetOwnedDiscordGuildsConnectionsDiscordGuildsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Discord Channels
 */
export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse200 =
  {
    data: GuildChannel[];
    status: 200;
  };

export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse422 =
  {
    data: HTTPValidationError;
    status: 422;
  };

export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponseSuccess =
  getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse200 & {
    headers: Headers;
  };
export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponseError =
  getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse422 & {
    headers: Headers;
  };

export type getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse =
  | getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponseSuccess
  | getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponseError;

export const getGetDiscordChannelsConnectionsDiscordGuildIdChannelsGetUrl = (
  guildId: string,
) => {
  return `/connections/discord/${guildId}/channels`;
};

export const getDiscordChannelsConnectionsDiscordGuildIdChannelsGet = async (
  guildId: string,
  options?: RequestInit,
): Promise<getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse> => {
  return customFetch<getDiscordChannelsConnectionsDiscordGuildIdChannelsGetResponse>(
    getGetDiscordChannelsConnectionsDiscordGuildIdChannelsGetUrl(guildId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Delete Connection
 */
export type deleteConnectionConnectionsPlatformDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteConnectionConnectionsPlatformDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteConnectionConnectionsPlatformDeleteResponseSuccess =
  deleteConnectionConnectionsPlatformDeleteResponse200 & {
    headers: Headers;
  };
export type deleteConnectionConnectionsPlatformDeleteResponseError =
  deleteConnectionConnectionsPlatformDeleteResponse422 & {
    headers: Headers;
  };

export type deleteConnectionConnectionsPlatformDeleteResponse =
  | deleteConnectionConnectionsPlatformDeleteResponseSuccess
  | deleteConnectionConnectionsPlatformDeleteResponseError;

export const getDeleteConnectionConnectionsPlatformDeleteUrl = (
  platform: MessagePlatform,
) => {
  return `/connections/${platform}`;
};

export const deleteConnectionConnectionsPlatformDelete = async (
  platform: MessagePlatform,
  options?: RequestInit,
): Promise<deleteConnectionConnectionsPlatformDeleteResponse> => {
  return customFetch<deleteConnectionConnectionsPlatformDeleteResponse>(
    getDeleteConnectionConnectionsPlatformDeleteUrl(platform),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Create a new moderator for the authenticated user.
 * @summary Create Moderator
 */
export type createModeratorModeratorsPostResponse200 = {
  data: ModeratorResponse;
  status: 200;
};

export type createModeratorModeratorsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createModeratorModeratorsPostResponseSuccess =
  createModeratorModeratorsPostResponse200 & {
    headers: Headers;
  };
export type createModeratorModeratorsPostResponseError =
  createModeratorModeratorsPostResponse422 & {
    headers: Headers;
  };

export type createModeratorModeratorsPostResponse =
  | createModeratorModeratorsPostResponseSuccess
  | createModeratorModeratorsPostResponseError;

export const getCreateModeratorModeratorsPostUrl = () => {
  return `/moderators/`;
};

export const createModeratorModeratorsPost = async (
  moderatorCreate: ModeratorCreate,
  options?: RequestInit,
): Promise<createModeratorModeratorsPostResponse> => {
  return customFetch<createModeratorModeratorsPostResponse>(
    getCreateModeratorModeratorsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(moderatorCreate),
    },
  );
};

/**
 * List moderators with filtering and pagination.
 * @summary List Moderators
 */
export type listModeratorsModeratorsGetResponse200 = {
  data: PaginatedResponseModeratorResponse;
  status: 200;
};

export type listModeratorsModeratorsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listModeratorsModeratorsGetResponseSuccess =
  listModeratorsModeratorsGetResponse200 & {
    headers: Headers;
  };
export type listModeratorsModeratorsGetResponseError =
  listModeratorsModeratorsGetResponse422 & {
    headers: Headers;
  };

export type listModeratorsModeratorsGetResponse =
  | listModeratorsModeratorsGetResponseSuccess
  | listModeratorsModeratorsGetResponseError;

export const getListModeratorsModeratorsGetUrl = (
  params?: ListModeratorsModeratorsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/moderators/?${stringifiedParams}`
    : `/moderators/`;
};

export const listModeratorsModeratorsGet = async (
  params?: ListModeratorsModeratorsGetParams,
  options?: RequestInit,
): Promise<listModeratorsModeratorsGetResponse> => {
  return customFetch<listModeratorsModeratorsGetResponse>(
    getListModeratorsModeratorsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Get a moderator by ID.
 * @summary Get Moderator
 */
export type getModeratorModeratorsModeratorIdGetResponse200 = {
  data: ModeratorResponse;
  status: 200;
};

export type getModeratorModeratorsModeratorIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getModeratorModeratorsModeratorIdGetResponseSuccess =
  getModeratorModeratorsModeratorIdGetResponse200 & {
    headers: Headers;
  };
export type getModeratorModeratorsModeratorIdGetResponseError =
  getModeratorModeratorsModeratorIdGetResponse422 & {
    headers: Headers;
  };

export type getModeratorModeratorsModeratorIdGetResponse =
  | getModeratorModeratorsModeratorIdGetResponseSuccess
  | getModeratorModeratorsModeratorIdGetResponseError;

export const getGetModeratorModeratorsModeratorIdGetUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const getModeratorModeratorsModeratorIdGet = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<getModeratorModeratorsModeratorIdGetResponse> => {
  return customFetch<getModeratorModeratorsModeratorIdGetResponse>(
    getGetModeratorModeratorsModeratorIdGetUrl(moderatorId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Update a moderator's name, description, or configuration.
 * @summary Update Moderator
 */
export type updateModeratorModeratorsModeratorIdPatchResponse200 = {
  data: ModeratorResponse;
  status: 200;
};

export type updateModeratorModeratorsModeratorIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateModeratorModeratorsModeratorIdPatchResponseSuccess =
  updateModeratorModeratorsModeratorIdPatchResponse200 & {
    headers: Headers;
  };
export type updateModeratorModeratorsModeratorIdPatchResponseError =
  updateModeratorModeratorsModeratorIdPatchResponse422 & {
    headers: Headers;
  };

export type updateModeratorModeratorsModeratorIdPatchResponse =
  | updateModeratorModeratorsModeratorIdPatchResponseSuccess
  | updateModeratorModeratorsModeratorIdPatchResponseError;

export const getUpdateModeratorModeratorsModeratorIdPatchUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const updateModeratorModeratorsModeratorIdPatch = async (
  moderatorId: string,
  moderatorUpdate: ModeratorUpdate,
  options?: RequestInit,
): Promise<updateModeratorModeratorsModeratorIdPatchResponse> => {
  return customFetch<updateModeratorModeratorsModeratorIdPatchResponse>(
    getUpdateModeratorModeratorsModeratorIdPatchUrl(moderatorId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(moderatorUpdate),
    },
  );
};

/**
 * Delete a moderator. Only allowed if moderator is offline.
 * @summary Delete Moderator
 */
export type deleteModeratorModeratorsModeratorIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteModeratorModeratorsModeratorIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteModeratorModeratorsModeratorIdDeleteResponseSuccess =
  deleteModeratorModeratorsModeratorIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteModeratorModeratorsModeratorIdDeleteResponseError =
  deleteModeratorModeratorsModeratorIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteModeratorModeratorsModeratorIdDeleteResponse =
  | deleteModeratorModeratorsModeratorIdDeleteResponseSuccess
  | deleteModeratorModeratorsModeratorIdDeleteResponseError;

export const getDeleteModeratorModeratorsModeratorIdDeleteUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}`;
};

export const deleteModeratorModeratorsModeratorIdDelete = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<deleteModeratorModeratorsModeratorIdDeleteResponse> => {
  return customFetch<deleteModeratorModeratorsModeratorIdDeleteResponse>(
    getDeleteModeratorModeratorsModeratorIdDeleteUrl(moderatorId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Get moderator statistics for a given timeframe.
 * @summary Get Moderator Stats
 */
export type getModeratorStatsModeratorsModeratorIdStatsGetResponse200 = {
  data: ModeratorStats;
  status: 200;
};

export type getModeratorStatsModeratorsModeratorIdStatsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getModeratorStatsModeratorsModeratorIdStatsGetResponseSuccess =
  getModeratorStatsModeratorsModeratorIdStatsGetResponse200 & {
    headers: Headers;
  };
export type getModeratorStatsModeratorsModeratorIdStatsGetResponseError =
  getModeratorStatsModeratorsModeratorIdStatsGetResponse422 & {
    headers: Headers;
  };

export type getModeratorStatsModeratorsModeratorIdStatsGetResponse =
  | getModeratorStatsModeratorsModeratorIdStatsGetResponseSuccess
  | getModeratorStatsModeratorsModeratorIdStatsGetResponseError;

export const getGetModeratorStatsModeratorsModeratorIdStatsGetUrl = (
  moderatorId: string,
  params?: GetModeratorStatsModeratorsModeratorIdStatsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/moderators/${moderatorId}/stats?${stringifiedParams}`
    : `/moderators/${moderatorId}/stats`;
};

export const getModeratorStatsModeratorsModeratorIdStatsGet = async (
  moderatorId: string,
  params?: GetModeratorStatsModeratorsModeratorIdStatsGetParams,
  options?: RequestInit,
): Promise<getModeratorStatsModeratorsModeratorIdStatsGetResponse> => {
  return customFetch<getModeratorStatsModeratorsModeratorIdStatsGetResponse>(
    getGetModeratorStatsModeratorsModeratorIdStatsGetUrl(moderatorId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * List actions for a moderator with filtering and pagination.
 * @summary List Moderator Actions
 */
export type listModeratorActionsModeratorsModeratorIdActionsGetResponse200 = {
  data: PaginatedResponseActionResponse;
  status: 200;
};

export type listModeratorActionsModeratorsModeratorIdActionsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listModeratorActionsModeratorsModeratorIdActionsGetResponseSuccess =
  listModeratorActionsModeratorsModeratorIdActionsGetResponse200 & {
    headers: Headers;
  };
export type listModeratorActionsModeratorsModeratorIdActionsGetResponseError =
  listModeratorActionsModeratorsModeratorIdActionsGetResponse422 & {
    headers: Headers;
  };

export type listModeratorActionsModeratorsModeratorIdActionsGetResponse =
  | listModeratorActionsModeratorsModeratorIdActionsGetResponseSuccess
  | listModeratorActionsModeratorsModeratorIdActionsGetResponseError;

export const getListModeratorActionsModeratorsModeratorIdActionsGetUrl = (
  moderatorId: string,
  params?: ListModeratorActionsModeratorsModeratorIdActionsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/moderators/${moderatorId}/actions?${stringifiedParams}`
    : `/moderators/${moderatorId}/actions`;
};

export const listModeratorActionsModeratorsModeratorIdActionsGet = async (
  moderatorId: string,
  params?: ListModeratorActionsModeratorsModeratorIdActionsGetParams,
  options?: RequestInit,
): Promise<listModeratorActionsModeratorsModeratorIdActionsGetResponse> => {
  return customFetch<listModeratorActionsModeratorsModeratorIdActionsGetResponse>(
    getListModeratorActionsModeratorsModeratorIdActionsGetUrl(
      moderatorId,
      params,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Start a moderator.
 * @summary Start Moderator
 */
export type startModeratorModeratorsModeratorIdStartPostResponse202 = {
  data: unknown;
  status: 202;
};

export type startModeratorModeratorsModeratorIdStartPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type startModeratorModeratorsModeratorIdStartPostResponseSuccess =
  startModeratorModeratorsModeratorIdStartPostResponse202 & {
    headers: Headers;
  };
export type startModeratorModeratorsModeratorIdStartPostResponseError =
  startModeratorModeratorsModeratorIdStartPostResponse422 & {
    headers: Headers;
  };

export type startModeratorModeratorsModeratorIdStartPostResponse =
  | startModeratorModeratorsModeratorIdStartPostResponseSuccess
  | startModeratorModeratorsModeratorIdStartPostResponseError;

export const getStartModeratorModeratorsModeratorIdStartPostUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}/start`;
};

export const startModeratorModeratorsModeratorIdStartPost = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<startModeratorModeratorsModeratorIdStartPostResponse> => {
  return customFetch<startModeratorModeratorsModeratorIdStartPostResponse>(
    getStartModeratorModeratorsModeratorIdStartPostUrl(moderatorId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * Stop a running moderator.
 * @summary Stop Moderator
 */
export type stopModeratorModeratorsModeratorIdStopPostResponse202 = {
  data: unknown;
  status: 202;
};

export type stopModeratorModeratorsModeratorIdStopPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type stopModeratorModeratorsModeratorIdStopPostResponseSuccess =
  stopModeratorModeratorsModeratorIdStopPostResponse202 & {
    headers: Headers;
  };
export type stopModeratorModeratorsModeratorIdStopPostResponseError =
  stopModeratorModeratorsModeratorIdStopPostResponse422 & {
    headers: Headers;
  };

export type stopModeratorModeratorsModeratorIdStopPostResponse =
  | stopModeratorModeratorsModeratorIdStopPostResponseSuccess
  | stopModeratorModeratorsModeratorIdStopPostResponseError;

export const getStopModeratorModeratorsModeratorIdStopPostUrl = (
  moderatorId: string,
) => {
  return `/moderators/${moderatorId}/stop`;
};

export const stopModeratorModeratorsModeratorIdStopPost = async (
  moderatorId: string,
  options?: RequestInit,
): Promise<stopModeratorModeratorsModeratorIdStopPostResponse> => {
  return customFetch<stopModeratorModeratorsModeratorIdStopPostResponse>(
    getStopModeratorModeratorsModeratorIdStopPostUrl(moderatorId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * List behavior scores for all users in a moderator's guild with pagination.
 * @summary List Behavior Scores
 */
export type listBehaviorScoresModeratorsModeratorIdScoresGetResponse200 = {
  data: PaginatedResponseBehaviorScoreResponse;
  status: 200;
};

export type listBehaviorScoresModeratorsModeratorIdScoresGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listBehaviorScoresModeratorsModeratorIdScoresGetResponseSuccess =
  listBehaviorScoresModeratorsModeratorIdScoresGetResponse200 & {
    headers: Headers;
  };
export type listBehaviorScoresModeratorsModeratorIdScoresGetResponseError =
  listBehaviorScoresModeratorsModeratorIdScoresGetResponse422 & {
    headers: Headers;
  };

export type listBehaviorScoresModeratorsModeratorIdScoresGetResponse =
  | listBehaviorScoresModeratorsModeratorIdScoresGetResponseSuccess
  | listBehaviorScoresModeratorsModeratorIdScoresGetResponseError;

export const getListBehaviorScoresModeratorsModeratorIdScoresGetUrl = (
  moderatorId: string,
  params?: ListBehaviorScoresModeratorsModeratorIdScoresGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/moderators/${moderatorId}/scores?${stringifiedParams}`
    : `/moderators/${moderatorId}/scores`;
};

export const listBehaviorScoresModeratorsModeratorIdScoresGet = async (
  moderatorId: string,
  params?: ListBehaviorScoresModeratorsModeratorIdScoresGetParams,
  options?: RequestInit,
): Promise<listBehaviorScoresModeratorsModeratorIdScoresGetResponse> => {
  return customFetch<listBehaviorScoresModeratorsModeratorIdScoresGetResponse>(
    getListBehaviorScoresModeratorsModeratorIdScoresGetUrl(moderatorId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Get behavior score for a specific user in a moderator's guild.
 * @summary Get User Behavior Score
 */
export type getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponse200 =
  {
    data: BehaviorScoreResponse;
    status: 200;
  };

export type getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponse422 =
  {
    data: HTTPValidationError;
    status: 422;
  };

export type getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponseSuccess =
  getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponse200 & {
    headers: Headers;
  };
export type getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponseError =
  getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponse422 & {
    headers: Headers;
  };

export type getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponse =
  | getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponseSuccess
  | getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponseError;

export const getGetUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetUrl = (
  moderatorId: string,
  userId: string,
) => {
  return `/moderators/${moderatorId}/scores/${userId}`;
};

export const getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGet = async (
  moderatorId: string,
  userId: string,
  options?: RequestInit,
): Promise<getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponse> => {
  return customFetch<getUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetResponse>(
    getGetUserBehaviorScoreModeratorsModeratorIdScoresUserIdGetUrl(
      moderatorId,
      userId,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Generate a Stripe Checkout link for a given user and pricing tier.
 * @summary Get Payment Link
 */
export type getPaymentLinkPaymentsPaymentLinkGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getPaymentLinkPaymentsPaymentLinkGetResponseSuccess =
  getPaymentLinkPaymentsPaymentLinkGetResponse200 & {
    headers: Headers;
  };
export type getPaymentLinkPaymentsPaymentLinkGetResponse =
  getPaymentLinkPaymentsPaymentLinkGetResponseSuccess;

export const getGetPaymentLinkPaymentsPaymentLinkGetUrl = () => {
  return `/payments/payment-link`;
};

export const getPaymentLinkPaymentsPaymentLinkGet = async (
  options?: RequestInit,
): Promise<getPaymentLinkPaymentsPaymentLinkGetResponse> => {
  return customFetch<getPaymentLinkPaymentsPaymentLinkGetResponse>(
    getGetPaymentLinkPaymentsPaymentLinkGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Stripe webhook endpoint for handling subscription events.
 * @summary Stripe Webhook
 */
export type stripeWebhookPaymentsStripeWebhookPostResponse200 = {
  data: unknown;
  status: 200;
};

export type stripeWebhookPaymentsStripeWebhookPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type stripeWebhookPaymentsStripeWebhookPostResponseSuccess =
  stripeWebhookPaymentsStripeWebhookPostResponse200 & {
    headers: Headers;
  };
export type stripeWebhookPaymentsStripeWebhookPostResponseError =
  stripeWebhookPaymentsStripeWebhookPostResponse422 & {
    headers: Headers;
  };

export type stripeWebhookPaymentsStripeWebhookPostResponse =
  | stripeWebhookPaymentsStripeWebhookPostResponseSuccess
  | stripeWebhookPaymentsStripeWebhookPostResponseError;

export const getStripeWebhookPaymentsStripeWebhookPostUrl = () => {
  return `/payments/stripe/webhook`;
};

export const stripeWebhookPaymentsStripeWebhookPost = async (
  options?: RequestInit,
): Promise<stripeWebhookPaymentsStripeWebhookPostResponse> => {
  return customFetch<stripeWebhookPaymentsStripeWebhookPostResponse>(
    getStripeWebhookPaymentsStripeWebhookPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Contact Us
 */
export type contactUsPublicContactUsPostResponse202 = {
  data: unknown;
  status: 202;
};

export type contactUsPublicContactUsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type contactUsPublicContactUsPostResponseSuccess =
  contactUsPublicContactUsPostResponse202 & {
    headers: Headers;
  };
export type contactUsPublicContactUsPostResponseError =
  contactUsPublicContactUsPostResponse422 & {
    headers: Headers;
  };

export type contactUsPublicContactUsPostResponse =
  | contactUsPublicContactUsPostResponseSuccess
  | contactUsPublicContactUsPostResponseError;

export const getContactUsPublicContactUsPostUrl = () => {
  return `/public/contact-us`;
};

export const contactUsPublicContactUsPost = async (
  contactForm: ContactForm,
  options?: RequestInit,
): Promise<contactUsPublicContactUsPostResponse> => {
  return customFetch<contactUsPublicContactUsPostResponse>(
    getContactUsPublicContactUsPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(contactForm),
    },
  );
};
